#!/bin/sh

# Managed by gcc-config-2.12.2

# Call the appropriate C compiler with options to accept ANSI/ISO C
# The following options are the same (as of gcc-3.3):
# 	-std=c99
# 	-std=c9x
# 	-std=iso9899:1999
# 	-std=iso9899:199x

for i; do
    case "$i" in
	-std=c9[9x]|-std=iso9899:199[9x])
	    ;;
	-ansi|-std=*)
	    echo >&2 "`basename $0` called with non ANSI/ISO C99 option $i"
	    exit 1
	    ;;
    esac
done

exec x86_64-pc-linux-gnu-gcc -std=c99 -pedantic -U_FORTIFY_SOURCE ${1+"$@"}
