# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 17.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.



# The name this table is to be known by, with the format of the mappings in
# the main body of the table, and what all code points missing from this file
# map to.
$Unicode::UCD::SwashInfo{'ToIdentifierType'}{'format'} = 'sw'; # string, but some elements are interpreted as a list; white space occurs only as list item separators
$Unicode::UCD::SwashInfo{'ToIdentifierType'}{'missing'} = 'Not_Character';

return <<'END';
9	D	Not_XID
20	26	Not_XID
27		Inclusion
28	2C	Not_XID
2D	2E	Inclusion
2F		Not_XID
30	39	Recommended
3A		Inclusion
3B	40	Not_XID
41	5A	Recommended
5B	5E	Not_XID
5F		Recommended
60		Not_XID
61	7A	Recommended
7B	7E	Not_XID
85		Not_XID
A0		Not_NFKC
A1	A7	Not_XID
A8		Not_NFKC
A9		Not_XID
AA		Not_NFKC
AB	AC	Not_XID
AD		Default_Ignorable
AE		Not_XID
AF		Not_NFKC
B0	B1	Not_XID
B2	B5	Not_NFKC
B6		Not_XID
B7		Inclusion
B8	BA	Not_NFKC
BB		Not_XID
BC	BE	Not_NFKC
BF		Not_XID
C0	D6	Recommended
D7		Not_XID
D8	F6	Recommended
F7		Not_XID
F8	113	Recommended
114	115	Uncommon_Use
116	12B	Recommended
12C	12D	Uncommon_Use
12E	131	Recommended
132	133	Not_NFKC
134	137	Recommended
138		Obsolete
139	13E	Recommended
13F	140	Not_NFKC
141	148	Recommended
149		Deprecated
14A	14D	Recommended
14E	14F	Uncommon_Use
150	155	Recommended
156	157	Uncommon_Use
158	161	Recommended
162	163	Uncommon_Use
164	17E	Recommended
17F		Not_NFKC
180		Technical
181		Recommended
182	185	Uncommon_Use
186		Recommended
187	188	Uncommon_Use
189	18A	Recommended
18B	18C	Uncommon_Use
18D		Technical Obsolete
18E	192	Recommended
193		Uncommon_Use
194		Recommended
195		Uncommon_Use
196	199	Recommended
19A	19C	Uncommon_Use
19D		Recommended
19E	19F	Uncommon_Use
1A0	1A1	Recommended
1A2	1A9	Uncommon_Use
1AA	1AB	Technical Obsolete
1AC	1AE	Uncommon_Use
1AF	1B0	Recommended
1B1		Uncommon_Use
1B2	1B4	Recommended
1B5	1B6	Uncommon_Use
1B7		Recommended
1B8		Uncommon_Use
1B9		Obsolete
1BA	1BB	Technical Obsolete
1BC	1BD	Uncommon_Use
1BE		Technical Obsolete
1BF		Obsolete
1C0	1C3	Technical
1C4	1CC	Not_NFKC
1CD	1D4	Recommended
1D5	1DC	Uncommon_Use
1DD		Recommended
1DE	1E5	Uncommon_Use
1E6	1E9	Recommended
1EA	1ED	Uncommon_Use
1EE	1EF	Recommended
1F0		Uncommon_Use
1F1	1F3	Not_NFKC
1F4	1F5	Uncommon_Use
1F6	1F7	Obsolete
1F8	1F9	Recommended
1FA	1FF	Uncommon_Use
200	217	Technical
218	21B	Recommended
21C	21D	Obsolete
21E	233	Uncommon_Use
234	236	Technical
237	243	Uncommon_Use
244		Recommended
245	24B	Uncommon_Use
24C	24D	Recommended
24E	24F	Uncommon_Use
250	252	Technical
253	254	Recommended
255		Technical
256	257	Recommended
258		Technical
259		Recommended
25A		Technical
25B		Recommended
25C	262	Technical
263		Recommended
264	267	Technical
268	269	Recommended
26A	271	Technical
272		Recommended
273	276	Technical
277		Technical Obsolete
278	27B	Technical
27C		Technical Obsolete
27D	288	Technical
289		Recommended
28A		Technical
28B		Recommended
28C	291	Technical
292		Recommended
293	29D	Technical
29E		Technical Obsolete
29F	2AF	Technical
2B0	2B8	Not_NFKC
2B9	2BA	Technical
2BB	2BC	Inclusion
2BD	2C1	Technical
2C2	2C5	Not_XID
2C6	2D1	Technical
2D2	2D7	Not_XID
2D8	2DD	Not_NFKC
2DE	2DF	Not_XID
2E0	2E4	Not_NFKC
2E5	2E9	Not_XID
2EA	2EB	Limited_Use Not_XID
2EC		Technical
2ED		Not_XID
2EE		Technical
2EF	2FF	Not_XID
300	304	Recommended
305		Uncommon_Use
306	30C	Recommended
30D		Uncommon_Use
30E	315	Technical
316		Uncommon_Use
317	31A	Technical
31B		Recommended
31C	320	Technical
321	322	Uncommon_Use
323		Recommended
324	325	Technical
326	328	Recommended
329	330	Technical
331		Recommended
332		Uncommon_Use
333		Technical
334		Uncommon_Use
335		Technical
336		Uncommon_Use
337	33F	Technical
340	341	Not_NFKC
342		Technical
343	344	Not_NFKC
345		Obsolete
346	34E	Technical
34F		Default_Ignorable
350	357	Technical
358		Uncommon_Use
359	362	Technical
363	373	Obsolete
374		Not_NFKC
375		Technical Not_XID
376	377	Obsolete
37A		Not_NFKC
37B	37D	Obsolete
37E		Not_NFKC
37F		Obsolete
384	385	Not_NFKC
386		Recommended
387		Not_NFKC
388	38A	Recommended
38C		Recommended
38E	3A1	Recommended
3A3	3CE	Recommended
3CF		Technical
3D0	3D6	Not_NFKC
3D7		Technical
3D8	3E1	Obsolete
3E2	3EF	Exclusion
3F0	3F2	Not_NFKC
3F3		Technical Obsolete
3F4	3F5	Not_NFKC
3F6		Not_XID
3F7	3F8	Obsolete
3F9		Not_NFKC
3FA	3FB	Obsolete
3FC		Technical Obsolete
3FD	3FF	Obsolete
400		Uncommon_Use
401	40C	Recommended
40D		Uncommon_Use
40E	44F	Recommended
450		Uncommon_Use
451	45C	Recommended
45D		Uncommon_Use
45E	45F	Recommended
460	481	Obsolete
482		Obsolete Not_XID
483		Obsolete
484	487	Technical Obsolete
488	489	Obsolete Not_XID
48A	48F	Uncommon_Use
490	49B	Recommended
49C	49D	Obsolete
49E	4A5	Recommended
4A6	4A7	Obsolete
4A8	4B7	Recommended
4B8	4B9	Obsolete
4BA	4C0	Recommended
4C1	4CE	Uncommon_Use
4CF	4D9	Recommended
4DA	4DB	Uncommon_Use
4DC	4E9	Recommended
4EA	4ED	Uncommon_Use
4EE	4F5	Recommended
4F6	4F7	Uncommon_Use
4F8	4F9	Recommended
4FA	4FF	Uncommon_Use
500	50F	Obsolete
510	513	Uncommon_Use
514	523	Obsolete
524	525	Recommended
526	52F	Obsolete
531	556	Recommended
559		Technical
55A	55F	Not_XID
560		Technical
561	586	Recommended
587		Not_NFKC
588		Technical
589		Not_XID
58A		Inclusion
58D	58F	Not_XID
591	5A1	Uncommon_Use
5A2		Uncommon_Use Obsolete
5A3	5BD	Uncommon_Use
5BE		Not_XID
5BF		Uncommon_Use
5C0		Not_XID
5C1	5C2	Uncommon_Use
5C3		Not_XID
5C4		Uncommon_Use
5C5		Uncommon_Use Obsolete
5C6		Obsolete Not_XID
5C7		Uncommon_Use Technical
5D0	5EA	Recommended
5EF	5F2	Uncommon_Use
5F3	5F4	Inclusion
600	60F	Not_XID
610	61A	Uncommon_Use
61B		Not_XID
61C		Default_Ignorable
61D	61F	Not_XID
620	63A	Recommended
63B	63C	Obsolete
63D		Recommended
63E	640	Obsolete
641	652	Recommended
653		Uncommon_Use Technical
654	655	Recommended
656	65F	Uncommon_Use
660	669	Recommended
66A	66D	Not_XID
66E	66F	Obsolete
670		Recommended
671		Technical
672		Recommended
673		Deprecated
674		Recommended
675	678	Not_NFKC
679	68F	Recommended
690		Obsolete
691	69A	Recommended
69B	69E	Uncommon_Use
69F	6A0	Recommended
6A1		Uncommon_Use
6A2		Recommended
6A3		Uncommon_Use
6A4	6AB	Recommended
6AC		Obsolete
6AD	6B1	Recommended
6B2		Uncommon_Use
6B3		Recommended
6B4		Uncommon_Use
6B5	6B7	Recommended
6B8	6B9	Uncommon_Use
6BA	6BE	Recommended
6BF		Uncommon_Use
6C0	6D3	Recommended
6D4		Not_XID
6D5		Recommended
6D6	6DC	Uncommon_Use
6DD	6DE	Not_XID
6DF	6E4	Uncommon_Use
6E5	6E6	Technical
6E7	6E8	Uncommon_Use
6E9		Not_XID
6EA	6ED	Uncommon_Use
6EE	6F9	Recommended
6FA	6FC	Uncommon_Use
6FD	6FE	Inclusion
6FF		Recommended
700	70D	Limited_Use Not_XID
70F		Limited_Use Not_XID
710	73F	Limited_Use
740	74A	Limited_Use Technical
74D	74F	Limited_Use
750		Uncommon_Use
751	752	Recommended
753	755	Uncommon_Use
756		Recommended
757	75F	Uncommon_Use
760		Recommended
761		Uncommon_Use
762	763	Recommended
764	765	Uncommon_Use
766	768	Recommended
769		Uncommon_Use
76A		Recommended
76B	76D	Uncommon_Use
76E	771	Recommended
772	77D	Uncommon_Use
77E	77F	Obsolete
780	7B1	Recommended
7C0	7E7	Limited_Use
7E8	7EA	Limited_Use Obsolete
7EB	7F5	Limited_Use
7F6	7F9	Limited_Use Not_XID
7FA		Limited_Use Obsolete
7FD		Limited_Use
7FE	7FF	Limited_Use Not_XID
800	82D	Exclusion
830	83E	Exclusion Not_XID
840	85B	Limited_Use
85E		Limited_Use Not_XID
860	86A	Limited_Use
870	887	Technical
888		Technical Not_XID
889	88D	Uncommon_Use
88E		Obsolete
88F		Recommended
890	891	Not_XID
897	89F	Uncommon_Use
8A0		Recommended
8A1		Uncommon_Use
8A2	8A9	Recommended
8AA	8AC	Uncommon_Use
8AD	8B1	Obsolete
8B2	8B4	Uncommon_Use
8B5		Obsolete
8B6	8BA	Uncommon_Use
8BB	8C2	Recommended
8C3	8C6	Uncommon_Use
8C7		Recommended
8C8		Uncommon_Use
8C9		Technical
8CA	8E1	Uncommon_Use
8E2		Not_XID
8E3	900	Uncommon_Use
901	903	Recommended
904		Uncommon_Use
905	90B	Recommended
90C		Obsolete
90D	928	Recommended
929		Uncommon_Use
92A	933	Recommended
934		Uncommon_Use
935	93C	Recommended
93D		Obsolete
93E	943	Recommended
944		Uncommon_Use
945	94D	Recommended
94E		Obsolete
94F		Recommended
950		Technical
951	952	Obsolete
953	954	Technical
955		Uncommon_Use
956	957	Recommended
958	95F	Not_NFKC
960	963	Obsolete
964	965	Not_XID
966	96F	Recommended
970		Not_XID
971		Obsolete
972	977	Recommended
978		Obsolete
979	97A	Uncommon_Use
97B	97C	Recommended
97D		Technical
97E	97F	Recommended
980		Obsolete
981	983	Recommended
985	98B	Recommended
98C		Uncommon_Use
98F	990	Recommended
993	9A8	Recommended
9AA	9B0	Recommended
9B2		Recommended
9B6	9B9	Recommended
9BC		Recommended
9BD		Obsolete
9BE	9C4	Recommended
9C7	9C8	Recommended
9CB	9CE	Recommended
9D7		Uncommon_Use
9DC	9DD	Not_NFKC
9DF		Not_NFKC
9E0	9E3	Obsolete
9E6	9F1	Recommended
9F2	9FB	Not_XID
9FC		Obsolete
9FD		Not_XID
9FE		Uncommon_Use
A01		Uncommon_Use
A02		Recommended
A03		Uncommon_Use
A05	A0A	Recommended
A0F	A10	Recommended
A13	A28	Recommended
A2A	A30	Recommended
A32		Recommended
A33		Not_NFKC
A35		Recommended
A36		Not_NFKC
A38	A39	Recommended
A3C		Recommended
A3E	A42	Recommended
A47	A48	Recommended
A4B	A4D	Recommended
A51		Uncommon_Use
A59	A5B	Not_NFKC
A5C		Recommended
A5E		Not_NFKC
A66	A6F	Uncommon_Use
A70	A71	Recommended
A72	A73	Uncommon_Use
A74		Technical
A75		Uncommon_Use
A76		Not_XID
A81		Uncommon_Use
A82	A83	Recommended
A85	A8D	Recommended
A8F	A91	Recommended
A93	AA8	Recommended
AAA	AB0	Recommended
AB2	AB3	Recommended
AB5	AB9	Recommended
ABC		Recommended
ABD		Obsolete
ABE	AC5	Recommended
AC7	AC9	Recommended
ACB	ACD	Recommended
AD0		Technical
AE0	AE3	Obsolete
AE6	AEF	Recommended
AF0	AF1	Not_XID
AF9	AFF	Uncommon_Use
B01	B03	Recommended
B05	B0B	Recommended
B0C		Uncommon_Use
B0F	B10	Recommended
B13	B28	Recommended
B2A	B30	Recommended
B32	B33	Recommended
B35		Uncommon_Use
B36	B39	Recommended
B3C		Recommended
B3D		Obsolete
B3E	B43	Recommended
B44		Uncommon_Use
B47	B48	Recommended
B4B	B4D	Recommended
B55		Uncommon_Use
B56		Recommended
B57		Uncommon_Use
B5C	B5D	Not_NFKC
B5F		Recommended
B60	B61	Obsolete
B62	B63	Uncommon_Use
B66	B6F	Uncommon_Use
B70		Not_XID
B71		Recommended
B72	B77	Not_XID
B82		Technical
B83		Recommended
B85	B8A	Recommended
B8E	B90	Recommended
B92	B95	Recommended
B99	B9A	Recommended
B9C		Recommended
B9E	B9F	Recommended
BA3	BA4	Recommended
BA8	BAA	Recommended
BAE	BB9	Recommended
BBE	BC2	Recommended
BC6	BC8	Recommended
BCA	BCD	Recommended
BD0		Technical
BD7		Uncommon_Use
BE6	BEF	Uncommon_Use
BF0	BFA	Not_XID
C00		Obsolete
C01		Uncommon_Use
C02	C03	Recommended
C04		Uncommon_Use
C05	C0B	Recommended
C0C		Uncommon_Use
C0E	C10	Recommended
C12	C28	Recommended
C2A	C30	Recommended
C31		Uncommon_Use
C32	C33	Recommended
C34		Obsolete
C35	C39	Recommended
C3C		Uncommon_Use
C3D		Obsolete
C3E	C44	Recommended
C46	C48	Recommended
C4A	C4D	Recommended
C55	C56	Uncommon_Use
C58	C59	Obsolete
C5A		Uncommon_Use
C5C		Obsolete
C5D		Uncommon_Use
C60	C61	Obsolete
C62	C63	Uncommon_Use
C66	C6F	Uncommon_Use
C77	C7F	Not_XID
C80		Uncommon_Use
C81		Obsolete
C82	C83	Recommended
C84		Not_XID
C85	C8B	Recommended
C8C		Obsolete
C8E	C90	Recommended
C92	CA8	Recommended
CAA	CB0	Recommended
CB1		Obsolete
CB2	CB3	Recommended
CB5	CB9	Recommended
CBC		Uncommon_Use
CBD		Obsolete
CBE	CC3	Recommended
CC4		Uncommon_Use
CC6	CC8	Recommended
CCA	CCD	Recommended
CD5	CD6	Uncommon_Use
CDC		Obsolete
CDD		Uncommon_Use
CDE		Obsolete
CE0	CE3	Obsolete
CE6	CEF	Recommended
CF1	CF2	Obsolete
CF3		Uncommon_Use
D00		Uncommon_Use
D01		Obsolete
D02	D03	Recommended
D04		Technical Obsolete
D05	D0B	Recommended
D0C		Uncommon_Use
D0E	D10	Recommended
D12	D28	Recommended
D29		Uncommon_Use
D2A	D39	Recommended
D3A	D3D	Obsolete
D3E	D43	Recommended
D44		Uncommon_Use
D46	D48	Recommended
D4A	D4B	Recommended
D4C		Obsolete
D4D		Recommended
D4E		Obsolete
D4F		Not_XID
D54	D56	Uncommon_Use
D57		Recommended
D58	D5E	Not_XID
D5F	D61	Obsolete
D62	D63	Uncommon_Use
D66	D6F	Uncommon_Use
D70	D79	Not_XID
D7A	D7F	Recommended
D81		Technical
D82	D83	Recommended
D85	D8D	Recommended
D8E		Uncommon_Use
D8F	D90	Uncommon_Use Technical
D91	D96	Recommended
D9A	D9D	Recommended
D9E		Obsolete
D9F	DB1	Recommended
DB3	DBB	Recommended
DBD		Recommended
DC0	DC6	Recommended
DCA		Recommended
DCF	DD4	Recommended
DD6		Recommended
DD8	DDE	Recommended
DDF		Uncommon_Use Technical
DE6	DEF	Uncommon_Use
DF2		Recommended
DF3		Uncommon_Use Technical
DF4		Not_XID
E01	E32	Recommended
E33		Not_NFKC
E34	E3A	Recommended
E3F		Not_XID
E40	E4D	Recommended
E4E		Uncommon_Use
E4F		Not_XID
E50	E59	Recommended
E5A	E5B	Not_XID
E81	E82	Recommended
E84		Recommended
E86		Uncommon_Use
E87	E88	Recommended
E89		Uncommon_Use
E8A		Recommended
E8C		Uncommon_Use
E8D		Recommended
E8E	E93	Uncommon_Use
E94	E97	Recommended
E98		Uncommon_Use
E99	E9F	Recommended
EA0		Uncommon_Use
EA1	EA3	Recommended
EA5		Recommended
EA7		Recommended
EA8	EA9	Uncommon_Use
EAA	EAB	Recommended
EAC		Uncommon_Use
EAD	EAE	Recommended
EAF		Technical
EB0	EB2	Recommended
EB3		Not_NFKC
EB4	EB9	Recommended
EBA		Uncommon_Use
EBB	EBD	Recommended
EC0	EC4	Recommended
EC6		Recommended
EC8	ECD	Recommended
ECE		Uncommon_Use
ED0	ED9	Recommended
EDC	EDD	Not_NFKC
EDE	EDF	Uncommon_Use
F00		Technical
F01	F0A	Not_XID
F0B		Inclusion
F0C		Not_NFKC
F0D	F17	Not_XID
F18	F19	Technical
F1A	F1F	Not_XID
F20	F29	Recommended
F2A	F34	Not_XID
F35		Technical
F36		Not_XID
F37		Technical
F38		Not_XID
F39		Uncommon_Use
F3A	F3D	Not_XID
F3E	F3F	Technical
F40	F42	Recommended
F43		Not_NFKC
F44	F47	Recommended
F49	F4C	Recommended
F4D		Not_NFKC
F4E	F51	Recommended
F52		Not_NFKC
F53	F56	Recommended
F57		Not_NFKC
F58	F5B	Recommended
F5C		Not_NFKC
F5D	F68	Recommended
F69		Not_NFKC
F6A		Uncommon_Use Obsolete
F6B	F6C	Uncommon_Use
F71	F72	Recommended
F73		Not_NFKC
F74		Recommended
F75	F76	Not_NFKC
F77		Deprecated
F78		Not_NFKC
F79		Deprecated
F7A	F80	Recommended
F81		Not_NFKC
F82	F83	Uncommon_Use Obsolete
F84		Recommended
F85		Not_XID
F86	F8F	Obsolete
F90	F92	Recommended
F93		Not_NFKC
F94	F97	Recommended
F99	F9C	Recommended
F9D		Not_NFKC
F9E	FA1	Recommended
FA2		Not_NFKC
FA3	FA6	Recommended
FA7		Not_NFKC
FA8	FAB	Recommended
FAC		Not_NFKC
FAD		Recommended
FAE	FB0	Uncommon_Use
FB1	FB8	Recommended
FB9		Not_NFKC
FBA	FBC	Recommended
FBE	FC5	Not_XID
FC6		Uncommon_Use Technical
FC7	FCC	Not_XID
FCE	FDA	Not_XID
1000	1049	Recommended
104A	104F	Not_XID
1050	1059	Uncommon_Use Obsolete
105A	1064	Recommended
1065	1074	Uncommon_Use
1075	108A	Recommended
108B	108E	Uncommon_Use
108F		Recommended
1090	109D	Uncommon_Use
109E	109F	Not_XID
10A0	10C5	Obsolete
10C7		Recommended
10CD		Recommended
10D0	10F0	Recommended
10F1	10F6	Obsolete
10F7	10F8	Uncommon_Use
10F9	10FA	Uncommon_Use Technical
10FB		Not_XID
10FC		Not_NFKC
10FD	10FF	Uncommon_Use
1100	115E	Obsolete
115F	1160	Default_Ignorable
1161	11FF	Obsolete
1200	1206	Recommended
1207		Uncommon_Use
1208	1248	Recommended
124A	124D	Recommended
1250	1256	Recommended
1258		Recommended
125A	125D	Recommended
1260	1286	Recommended
1287		Uncommon_Use
1288		Recommended
128A	128D	Recommended
1290	12AE	Recommended
12AF		Uncommon_Use
12B0		Recommended
12B2	12B5	Recommended
12B8	12BE	Recommended
12C0		Recommended
12C2	12C5	Recommended
12C8	12D6	Recommended
12D8	12F7	Recommended
12F8	12FF	Uncommon_Use
1300	130E	Recommended
130F		Uncommon_Use
1310		Recommended
1312	1315	Recommended
1318	131E	Recommended
131F		Uncommon_Use
1320	1346	Recommended
1347		Uncommon_Use
1348	1359	Recommended
135A		Uncommon_Use
135D	135F	Uncommon_Use
1360	1368	Not_XID
1369	1371	Obsolete
1372	137C	Not_XID
1380	138F	Uncommon_Use
1390	1399	Not_XID
13A0	13F5	Limited_Use
13F8	13FD	Limited_Use
1400		Limited_Use Not_XID
1401	166C	Limited_Use
166D	166E	Limited_Use Not_XID
166F	167F	Limited_Use
1680		Exclusion Not_XID
1681	169A	Exclusion
169B	169C	Exclusion Not_XID
16A0	16EA	Exclusion
16EB	16ED	Exclusion Not_XID
16EE	16F8	Exclusion
1700	1715	Exclusion
171F	1734	Exclusion
1735	1736	Exclusion Not_XID
1740	1753	Exclusion
1760	176C	Exclusion
176E	1770	Exclusion
1772	1773	Exclusion
1780	179C	Recommended
179D	179E	Uncommon_Use
179F	17A2	Recommended
17A3	17A4	Deprecated
17A5	17A7	Recommended
17A8		Obsolete
17A9		Uncommon_Use
17AA	17B3	Recommended
17B4	17B5	Default_Ignorable
17B6	17CD	Recommended
17CE	17CF	Technical
17D0		Recommended
17D1		Technical Obsolete
17D2		Recommended
17D3		Obsolete
17D4	17D6	Not_XID
17D7		Uncommon_Use
17D8		Obsolete Not_XID
17D9	17DB	Not_XID
17DC		Obsolete
17DD		Technical Obsolete
17E0	17E9	Recommended
17F0	17F9	Not_XID
1800	180A	Exclusion Not_XID
180B	180F	Default_Ignorable
1810	1819	Exclusion
1820	1878	Exclusion
1880	18A8	Exclusion
18A9		Uncommon_Use Exclusion
18AA		Exclusion
18B0	18F5	Limited_Use
1900	191E	Limited_Use
1920	192B	Limited_Use
1930	193B	Limited_Use
1940		Limited_Use Not_XID
1944	1945	Limited_Use Not_XID
1946	196D	Limited_Use
1970	1974	Limited_Use
1980	19AB	Limited_Use
19B0	19C9	Limited_Use
19D0	19DA	Limited_Use
19DE	19DF	Limited_Use Not_XID
19E0	19FF	Not_XID
1A00	1A1B	Exclusion
1A1E	1A1F	Exclusion Not_XID
1A20	1A5E	Limited_Use
1A60	1A7C	Limited_Use
1A7F	1A89	Limited_Use
1A90	1A99	Limited_Use
1AA0	1AA6	Limited_Use Not_XID
1AA7		Limited_Use
1AA8	1AAD	Limited_Use Not_XID
1AB0	1ABD	Obsolete
1ABE		Not_XID
1ABF	1AC0	Technical
1AC1	1ACE	Uncommon_Use
1ACF	1ADD	Technical
1AE0	1AEB	Technical
1B00	1B4C	Limited_Use
1B4E	1B4F	Limited_Use Not_XID
1B50	1B59	Limited_Use
1B5A	1B6A	Limited_Use Not_XID
1B6B	1B73	Limited_Use Technical
1B74	1B7F	Limited_Use Not_XID
1B80	1BF3	Limited_Use
1BFC	1BFF	Limited_Use Not_XID
1C00	1C37	Limited_Use
1C3B	1C3F	Limited_Use Not_XID
1C40	1C49	Limited_Use
1C4D	1C7D	Limited_Use
1C7E	1C7F	Limited_Use Not_XID
1C80	1C88	Obsolete
1C89	1C8A	Uncommon_Use
1C90	1CBA	Recommended
1CBD	1CBF	Recommended
1CC0	1CC7	Limited_Use Not_XID
1CD0	1CD2	Obsolete
1CD3		Obsolete Not_XID
1CD4	1CF9	Obsolete
1CFA		Exclusion
1D00	1D2B	Technical
1D2C	1D2E	Not_NFKC
1D2F		Technical
1D30	1D3A	Not_NFKC
1D3B		Technical
1D3C	1D4D	Not_NFKC
1D4E		Technical
1D4F	1D6A	Not_NFKC
1D6B	1D77	Technical
1D78		Not_NFKC
1D79	1D9A	Technical
1D9B	1DBF	Not_NFKC
1DC0	1DC3	Technical Obsolete
1DC4	1DCD	Technical
1DCE		Technical Obsolete
1DCF	1DD0	Technical
1DD1	1DE6	Technical Obsolete
1DE7	1DF9	Technical
1DFA		Limited_Use Technical
1DFB	1E01	Technical
1E02	1E0B	Uncommon_Use
1E0C	1E0D	Recommended
1E0E	1E11	Uncommon_Use
1E12	1E13	Recommended
1E14	1E17	Uncommon_Use
1E18	1E1B	Technical
1E1C	1E1F	Uncommon_Use
1E20	1E21	Recommended
1E22	1E23	Uncommon_Use
1E24	1E25	Recommended
1E26	1E29	Uncommon_Use
1E2A	1E2D	Technical
1E2E	1E35	Uncommon_Use
1E36	1E37	Recommended
1E38	1E3B	Uncommon_Use
1E3C	1E3F	Recommended
1E40	1E41	Uncommon_Use
1E42	1E4B	Recommended
1E4C	1E59	Uncommon_Use
1E5A	1E5B	Recommended
1E5C	1E61	Uncommon_Use
1E62	1E63	Recommended
1E64	1E6B	Uncommon_Use
1E6C	1E6D	Recommended
1E6E	1E6F	Uncommon_Use
1E70	1E71	Recommended
1E72	1E77	Technical
1E78	1E8B	Uncommon_Use
1E8C	1E8D	Recommended
1E8E	1E91	Uncommon_Use
1E92	1E93	Recommended
1E94	1E99	Uncommon_Use
1E9A	1E9B	Not_NFKC
1E9C	1E9D	Technical
1E9E		Recommended
1E9F		Technical
1EA0	1EF9	Recommended
1EFA	1EFF	Technical
1F00	1F15	Obsolete
1F18	1F1D	Obsolete
1F20	1F45	Obsolete
1F48	1F4D	Obsolete
1F50	1F57	Obsolete
1F59		Obsolete
1F5B		Obsolete
1F5D		Obsolete
1F5F	1F70	Obsolete
1F71		Not_NFKC
1F72		Obsolete
1F73		Not_NFKC
1F74		Obsolete
1F75		Not_NFKC
1F76		Obsolete
1F77		Not_NFKC
1F78		Obsolete
1F79		Not_NFKC
1F7A		Obsolete
1F7B		Not_NFKC
1F7C		Obsolete
1F7D		Not_NFKC
1F80	1F9F	Obsolete
1FA0	1FAF	Recommended
1FB0	1FB1	Technical Obsolete
1FB2	1FB4	Recommended
1FB6	1FBA	Obsolete
1FBB		Not_NFKC
1FBC		Obsolete
1FBD	1FC1	Not_NFKC
1FC2	1FC4	Obsolete
1FC6	1FC8	Obsolete
1FC9		Not_NFKC
1FCA		Obsolete
1FCB		Not_NFKC
1FCC		Obsolete
1FCD	1FCF	Not_NFKC
1FD0	1FD2	Obsolete
1FD3		Not_NFKC
1FD6	1FDA	Obsolete
1FDB		Not_NFKC
1FDD	1FDF	Not_NFKC
1FE0	1FE2	Obsolete
1FE3		Not_NFKC
1FE4	1FEA	Obsolete
1FEB		Not_NFKC
1FEC		Recommended
1FED	1FEF	Not_NFKC
1FF2	1FF4	Obsolete
1FF6	1FF8	Obsolete
1FF9		Not_NFKC
1FFA		Obsolete
1FFB		Not_NFKC
1FFC		Obsolete
1FFD	1FFE	Not_NFKC
2000	200A	Not_NFKC
200B	200F	Default_Ignorable
2010		Inclusion
2011		Not_NFKC
2012	2016	Not_XID
2017		Not_NFKC
2018		Not_XID
2019		Inclusion
201A	2023	Not_XID
2024	2026	Not_NFKC
2027		Inclusion
2028	2029	Not_XID
202A	202E	Default_Ignorable
202F		Not_NFKC
2030	2032	Not_XID
2033	2034	Not_NFKC
2035		Not_XID
2036	2037	Not_NFKC
2038	203B	Not_XID
203C		Not_NFKC
203D		Not_XID
203E		Not_NFKC
203F	2040	Technical
2041	2046	Not_XID
2047	2049	Not_NFKC
204A	2053	Not_XID
2054		Uncommon_Use
2055		Not_XID
2056		Obsolete Not_XID
2057		Not_NFKC
2058	205E	Obsolete Not_XID
205F		Not_NFKC
2060	2064	Default_Ignorable
2066	2069	Default_Ignorable
206A	206F	Deprecated
2070	2071	Not_NFKC
2074	208E	Not_NFKC
2090	209C	Not_NFKC
20A0	20A7	Not_XID
20A8		Not_NFKC
20A9	20C1	Not_XID
20D0	20DC	Technical
20DD	20E0	Technical Not_XID
20E1		Technical
20E2	20E4	Technical Not_XID
20E5	20F0	Technical
2100	2103	Not_NFKC
2104		Not_XID
2105	2107	Not_NFKC
2108		Not_XID
2109	2113	Not_NFKC
2114		Not_XID
2115	2116	Not_NFKC
2117		Not_XID
2118		Technical
2119	211D	Not_NFKC
211E	211F	Not_XID
2120	2122	Not_NFKC
2123		Not_XID
2124		Not_NFKC
2125		Not_XID
2126		Not_NFKC
2127		Obsolete Not_XID
2128		Not_NFKC
2129		Not_XID
212A	212D	Not_NFKC
212E		Technical
212F	2131	Not_NFKC
2132		Obsolete
2133	2139	Not_NFKC
213A		Not_XID
213B	2140	Not_NFKC
2141	2144	Not_XID
2145	2149	Not_NFKC
214A	214D	Not_XID
214E		Obsolete
214F		Obsolete Not_XID
2150	217F	Not_NFKC
2180	2183	Technical Obsolete
2184	2188	Obsolete
2189		Not_NFKC
218A	218B	Uncommon_Use Not_XID
2190	222B	Not_XID
222C	222D	Not_NFKC
222E		Not_XID
222F	2230	Not_NFKC
2231	2328	Not_XID
2329	232A	Deprecated
232B	2429	Not_XID
2440	244A	Not_XID
2460	24EA	Not_NFKC
24EB	24FF	Technical Not_XID
2500	27FF	Not_XID
2800	28FF	Technical Not_XID
2900	2A0B	Not_XID
2A0C		Not_NFKC
2A0D	2A73	Not_XID
2A74	2A76	Not_NFKC
2A77	2ADB	Not_XID
2ADC		Not_NFKC
2ADD	2B73	Not_XID
2B76	2BEB	Not_XID
2BEC	2BEF	Uncommon_Use Not_XID
2BF0	2BFF	Not_XID
2C00	2C5F	Exclusion
2C60	2C67	Technical
2C68	2C6C	Uncommon_Use
2C6D	2C76	Obsolete
2C77	2C7B	Technical
2C7C	2C7D	Not_NFKC
2C7E	2C7F	Obsolete
2C80	2CE4	Exclusion
2CE5	2CEA	Exclusion Not_XID
2CEB	2CEF	Exclusion
2CF0	2CF1	Technical Exclusion
2CF2	2CF3	Exclusion
2CF9	2CFF	Exclusion Not_XID
2D00	2D25	Obsolete
2D27		Technical
2D2D		Technical
2D30	2D67	Limited_Use
2D6F		Not_NFKC
2D70		Limited_Use Not_XID
2D7F		Limited_Use
2D80	2D96	Uncommon_Use
2DA0	2DA6	Uncommon_Use
2DA8	2DAE	Uncommon_Use
2DB0	2DB6	Uncommon_Use
2DB8	2DBE	Uncommon_Use
2DC0	2DC6	Uncommon_Use
2DC8	2DCE	Uncommon_Use
2DD0	2DD6	Uncommon_Use
2DD8	2DDE	Uncommon_Use
2DE0	2DFF	Obsolete
2E00	2E0D	Technical Obsolete Not_XID
2E0E	2E16	Obsolete Not_XID
2E17	2E29	Not_XID
2E2A	2E2F	Obsolete Not_XID
2E30		Exclusion Not_XID
2E31	2E32	Obsolete Not_XID
2E33	2E34	Not_XID
2E35		Obsolete Not_XID
2E36	2E38	Not_XID
2E39		Obsolete Not_XID
2E3A	2E3B	Not_XID
2E3C		Exclusion Not_XID
2E3D	2E5D	Not_XID
2E80	2E99	Not_XID
2E9B	2E9E	Not_XID
2E9F		Not_NFKC
2EA0	2EF2	Not_XID
2EF3		Not_NFKC
2F00	2FD5	Not_NFKC
2FF0	2FFF	Not_XID
3000		Not_NFKC
3001	3004	Not_XID
3005	3007	Recommended
3008	301D	Not_XID
301E		Obsolete Not_XID
301F	3020	Not_XID
3021	302D	Technical
302E	302F	Technical Obsolete
3030		Not_XID
3031	3035	Technical
3036		Not_NFKC
3037		Not_XID
3038	303A	Not_NFKC
303B	303C	Technical
303D	303F	Not_XID
3041	3096	Recommended
3099	309A	Uncommon_Use
309B	309C	Not_NFKC
309D	309E	Recommended
309F		Not_NFKC
30A0		Inclusion
30A1	30FA	Recommended
30FB		Inclusion
30FC	30FE	Recommended
30FF		Not_NFKC
3105	312D	Limited_Use
312E		Limited_Use Obsolete
312F		Limited_Use
3131	3163	Not_NFKC
3164		Default_Ignorable
3165	318E	Not_NFKC
3190	3191	Not_XID
3192	319F	Not_NFKC
31A0	31BF	Limited_Use
31C0	31E5	Not_XID
31EF		Not_XID
31F0	31FF	Obsolete
3200	321E	Not_NFKC
3220	3247	Not_NFKC
3248	324F	Not_XID
3250	327E	Not_NFKC
327F		Technical Not_XID
3280	33FF	Not_NFKC
3400	3446	Uncommon_Use
3447		Recommended
3448	3472	Uncommon_Use
3473		Recommended
3474	34E3	Uncommon_Use
34E4		Recommended
34E5	3576	Uncommon_Use
3577		Recommended
3578	359D	Uncommon_Use
359E		Recommended
359F	35A0	Uncommon_Use
35A1		Recommended
35A2	35AC	Uncommon_Use
35AD		Recommended
35AE	35BE	Uncommon_Use
35BF		Recommended
35C0	35CD	Uncommon_Use
35CE		Recommended
35CF	35F2	Uncommon_Use
35F3		Recommended
35F4	35FD	Uncommon_Use
35FE		Recommended
35FF	360D	Uncommon_Use
360E		Recommended
360F	3619	Uncommon_Use
361A		Recommended
361B	3917	Uncommon_Use
3918		Recommended
3919	395F	Uncommon_Use
3960		Recommended
3961	396D	Uncommon_Use
396E		Recommended
396F	39CE	Uncommon_Use
39CF	39D0	Recommended
39D1	39DA	Uncommon_Use
39DB		Recommended
39DC	39DE	Uncommon_Use
39DF		Recommended
39E0	39F7	Uncommon_Use
39F8		Recommended
39F9	39FD	Uncommon_Use
39FE		Recommended
39FF	3A17	Uncommon_Use
3A18		Recommended
3A19	3A51	Uncommon_Use
3A52		Recommended
3A53	3A5B	Uncommon_Use
3A5C		Recommended
3A5D	3A66	Uncommon_Use
3A67		Recommended
3A68	3A72	Uncommon_Use
3A73		Recommended
3A74	3B38	Uncommon_Use
3B39		Recommended
3B3A	3B4D	Uncommon_Use
3B4E		Recommended
3B4F	3BA2	Uncommon_Use
3BA3		Recommended
3BA4	3C6D	Uncommon_Use
3C6E		Recommended
3C6F	3CDF	Uncommon_Use
3CE0		Recommended
3CE1	3DE6	Uncommon_Use
3DE7		Recommended
3DE8	3DEA	Uncommon_Use
3DEB		Recommended
3DEC	3E73	Uncommon_Use
3E74		Recommended
3E75	3ECF	Uncommon_Use
3ED0		Recommended
3ED1	4055	Uncommon_Use
4056		Recommended
4057	4064	Uncommon_Use
4065		Recommended
4066	4069	Uncommon_Use
406A		Recommended
406B	40BA	Uncommon_Use
40BB		Recommended
40BC	40DE	Uncommon_Use
40DF		Recommended
40E0	4136	Uncommon_Use
4137		Recommended
4138	415E	Uncommon_Use
415F		Recommended
4160	4336	Uncommon_Use
4337		Recommended
4338	43AB	Uncommon_Use
43AC		Recommended
43AD	43B0	Uncommon_Use
43B1		Recommended
43B2	43D2	Uncommon_Use
43D3		Recommended
43D4	43DC	Uncommon_Use
43DD		Recommended
43DE	4442	Uncommon_Use
4443		Recommended
4444	44D5	Uncommon_Use
44D6		Recommended
44D7	44E9	Uncommon_Use
44EA		Recommended
44EB	4605	Uncommon_Use
4606		Recommended
4607	464B	Uncommon_Use
464C		Recommended
464D	4660	Uncommon_Use
4661		Recommended
4662	4722	Uncommon_Use
4723		Recommended
4724	4728	Uncommon_Use
4729		Recommended
472A	477B	Uncommon_Use
477C		Recommended
477D	478C	Uncommon_Use
478D		Recommended
478E	47F3	Uncommon_Use
47F4		Recommended
47F5	4881	Uncommon_Use
4882		Recommended
4883	4946	Uncommon_Use
4947		Recommended
4948	4979	Uncommon_Use
497A		Recommended
497B	497C	Uncommon_Use
497D		Recommended
497E	4981	Uncommon_Use
4982	4983	Recommended
4984		Uncommon_Use
4985	4986	Recommended
4987	499A	Uncommon_Use
499B		Recommended
499C	499E	Uncommon_Use
499F		Recommended
49A0	49B5	Uncommon_Use
49B6	49B7	Recommended
49B8	4A11	Uncommon_Use
4A12		Recommended
4A13	4AB7	Uncommon_Use
4AB8		Recommended
4AB9	4C76	Uncommon_Use
4C77		Recommended
4C78	4C7C	Uncommon_Use
4C7D		Recommended
4C7E	4C80	Uncommon_Use
4C81		Recommended
4C82	4C84	Uncommon_Use
4C85		Recommended
4C86	4C9C	Uncommon_Use
4C9D	4CA3	Recommended
4CA4	4D12	Uncommon_Use
4D13	4D19	Recommended
4D1A	4DAD	Uncommon_Use
4DAE		Recommended
4DAF	4DBF	Uncommon_Use
4DC0	4DFF	Technical Not_XID
4E00	4E11	Recommended
4E12		Uncommon_Use
4E13	4E28	Recommended
4E29		Uncommon_Use
4E2A	4E67	Recommended
4E68		Uncommon_Use
4E69	4E78	Recommended
4E79		Uncommon_Use
4E7A	4E95	Recommended
4E96		Uncommon_Use
4E97	4EA2	Recommended
4EA3		Uncommon_Use
4EA4	4EBB	Recommended
4EBC		Uncommon_Use
4EBD	4ECB	Recommended
4ECC		Uncommon_Use
4ECD	4EE6	Recommended
4EE7		Uncommon_Use
4EE8	4EF7	Recommended
4EF8	4EFA	Uncommon_Use
4EFB		Recommended
4EFC		Uncommon_Use
4EFD		Recommended
4EFE		Uncommon_Use
4EFF	4F06	Recommended
4F07		Uncommon_Use
4F08	4F15	Recommended
4F16		Uncommon_Use
4F17	4F27	Recommended
4F28		Uncommon_Use
4F29	4F30	Recommended
4F31		Uncommon_Use
4F32	4F34	Recommended
4F35		Uncommon_Use
4F36		Recommended
4F37		Uncommon_Use
4F38	4F3F	Recommended
4F40		Uncommon_Use
4F41	4F43	Recommended
4F44		Uncommon_Use
4F45	4F70	Recommended
4F71		Uncommon_Use
4F72	4F8B	Recommended
4F8C		Uncommon_Use
4F8D		Recommended
4F8E		Uncommon_Use
4F8F	4FA1	Recommended
4FA2		Uncommon_Use
4FA3	4FBC	Recommended
4FBD		Uncommon_Use
4FBE	4FC5	Recommended
4FC6		Uncommon_Use
4FC7		Recommended
4FC8		Uncommon_Use
4FC9	4FCB	Recommended
4FCC		Uncommon_Use
4FCD	4FE1	Recommended
4FE2		Uncommon_Use
4FE3	4FFB	Recommended
4FFC	4FFD	Uncommon_Use
4FFE	500F	Recommended
5010		Uncommon_Use
5011	5033	Recommended
5034		Uncommon_Use
5035	5037	Recommended
5038		Uncommon_Use
5039	503C	Recommended
503D		Uncommon_Use
503E	5041	Recommended
5042		Uncommon_Use
5043	5051	Recommended
5052		Uncommon_Use
5053	5057	Recommended
5058		Uncommon_Use
5059	507B	Recommended
507C		Uncommon_Use
507D	5080	Recommended
5081		Uncommon_Use
5082	5092	Recommended
5093		Uncommon_Use
5094	5096	Recommended
5097		Uncommon_Use
5098	509E	Recommended
509F	50A1	Uncommon_Use
50A2	50B8	Recommended
50B9		Uncommon_Use
50BA	50C2	Recommended
50C3		Uncommon_Use
50C4	50D7	Recommended
50D8		Uncommon_Use
50D9	50DE	Recommended
50DF		Uncommon_Use
50E0		Recommended
50E1	50E2	Uncommon_Use
50E3	50EA	Recommended
50EB		Uncommon_Use
50EC	50F3	Recommended
50F4		Uncommon_Use
50F5	50F6	Recommended
50F7		Uncommon_Use
50F8	511A	Recommended
511B		Uncommon_Use
511C	5127	Recommended
5128		Uncommon_Use
5129	512A	Recommended
512B		Uncommon_Use
512C	5141	Recommended
5142		Uncommon_Use
5143	5149	Recommended
514A		Uncommon_Use
514B	514E	Recommended
514F		Uncommon_Use
5150	5152	Recommended
5153		Uncommon_Use
5154	5157	Recommended
5158		Uncommon_Use
5159	515F	Recommended
5160		Uncommon_Use
5161	5163	Recommended
5164		Uncommon_Use
5165	5171	Recommended
5172		Uncommon_Use
5173	517D	Recommended
517E		Uncommon_Use
517F	5182	Recommended
5183	5184	Uncommon_Use
5185	518D	Recommended
518E		Uncommon_Use
518F	51A0	Recommended
51A1		Uncommon_Use
51A2		Recommended
51A3		Uncommon_Use
51A4	51AC	Recommended
51AD		Uncommon_Use
51AE	51B7	Recommended
51B8		Uncommon_Use
51B9		Recommended
51BA		Uncommon_Use
51BB	51C1	Recommended
51C2		Uncommon_Use
51C3	51D1	Recommended
51D2	51D3	Uncommon_Use
51D4	51DE	Recommended
51DF		Uncommon_Use
51E0	51EB	Recommended
51EC		Uncommon_Use
51ED		Recommended
51EE		Uncommon_Use
51EF	51F1	Recommended
51F2		Uncommon_Use
51F3	5252	Recommended
5253		Uncommon_Use
5254	5265	Recommended
5266		Uncommon_Use
5267	5278	Recommended
5279		Uncommon_Use
527A	5284	Recommended
5285		Uncommon_Use
5286	528D	Recommended
528E		Uncommon_Use
528F	52C3	Recommended
52C4		Uncommon_Use
52C5	52C7	Recommended
52C8		Uncommon_Use
52C9	52CB	Recommended
52CC		Uncommon_Use
52CD		Recommended
52CE		Uncommon_Use
52CF	52D0	Recommended
52D1		Uncommon_Use
52D2	52D3	Recommended
52D4		Uncommon_Use
52D5	52E0	Recommended
52E1		Uncommon_Use
52E2	52E4	Recommended
52E5		Uncommon_Use
52E6	52ED	Recommended
52EE		Uncommon_Use
52EF	5302	Recommended
5303	5304	Uncommon_Use
5305	5317	Recommended
5318		Uncommon_Use
5319	531A	Recommended
531B		Uncommon_Use
531C	531D	Recommended
531E		Uncommon_Use
531F	5326	Recommended
5327		Uncommon_Use
5328		Recommended
5329		Uncommon_Use
532A	5331	Recommended
5332		Uncommon_Use
5333	5334	Recommended
5335	5336	Uncommon_Use
5337	5341	Recommended
5342		Uncommon_Use
5343	535A	Recommended
535B		Uncommon_Use
535C		Recommended
535D		Uncommon_Use
535E	5369	Recommended
536A		Uncommon_Use
536B	536C	Recommended
536D		Uncommon_Use
536E	537F	Recommended
5380		Uncommon_Use
5381	53A0	Recommended
53A1		Uncommon_Use
53A2	53A9	Recommended
53AA	53AB	Uncommon_Use
53AC	53AE	Recommended
53AF		Uncommon_Use
53B0	53B9	Recommended
53BA		Uncommon_Use
53BB	53C4	Recommended
53C5		Uncommon_Use
53C6	53CE	Recommended
53CF		Uncommon_Use
53D0	53DC	Recommended
53DD	53DE	Uncommon_Use
53DF	53E6	Recommended
53E7		Uncommon_Use
53E8	53FE	Recommended
53FF	5400	Uncommon_Use
5401	5419	Recommended
541A		Uncommon_Use
541B	5421	Recommended
5422		Uncommon_Use
5423	544B	Recommended
544C		Uncommon_Use
544D	545C	Recommended
545D		Uncommon_Use
545E	5468	Recommended
5469		Uncommon_Use
546A	5489	Recommended
548A		Uncommon_Use
548B	54B4	Recommended
54B5		Uncommon_Use
54B6	54F5	Recommended
54F6		Uncommon_Use
54F7	5514	Recommended
5515		Uncommon_Use
5516	5517	Recommended
5518	5519	Uncommon_Use
551A	5546	Recommended
5547		Uncommon_Use
5548	555F	Recommended
5560		Uncommon_Use
5561	5579	Recommended
557A		Uncommon_Use
557B	55DF	Recommended
55E0		Uncommon_Use
55E1	55F7	Recommended
55F8		Uncommon_Use
55F9	5609	Recommended
560A	560B	Uncommon_Use
560C	561F	Recommended
5620		Uncommon_Use
5621	562A	Recommended
562B		Uncommon_Use
562C	5636	Recommended
5637		Uncommon_Use
5638	563B	Recommended
563C		Uncommon_Use
563D	5643	Recommended
5644		Uncommon_Use
5645	564A	Recommended
564B		Uncommon_Use
564C	5650	Recommended
5651		Uncommon_Use
5652	5655	Recommended
5656		Uncommon_Use
5657	565E	Recommended
565F		Uncommon_Use
5660		Recommended
5661		Uncommon_Use
5662	5674	Recommended
5675		Uncommon_Use
5676	567C	Recommended
567D		Uncommon_Use
567E	5687	Recommended
5688		Uncommon_Use
5689	568A	Recommended
568B		Uncommon_Use
568C	5695	Recommended
5696		Uncommon_Use
5697	569D	Recommended
569E		Uncommon_Use
569F	56B9	Recommended
56BA		Uncommon_Use
56BB	56CE	Recommended
56CF		Uncommon_Use
56D0	56D8	Recommended
56D9		Uncommon_Use
56DA	56E5	Recommended
56E6		Uncommon_Use
56E7	56F5	Recommended
56F6		Uncommon_Use
56F7		Recommended
56F8		Uncommon_Use
56F9	56FA	Recommended
56FB	56FC	Uncommon_Use
56FD	5704	Recommended
5705		Uncommon_Use
5706	5710	Recommended
5711		Uncommon_Use
5712	5716	Recommended
5717		Uncommon_Use
5718	5720	Recommended
5721		Uncommon_Use
5722	5723	Recommended
5724		Uncommon_Use
5725	573C	Recommended
573D		Uncommon_Use
573E	5742	Recommended
5743		Uncommon_Use
5744	5747	Recommended
5748		Uncommon_Use
5749	5754	Recommended
5755	5756	Uncommon_Use
5757		Recommended
5758		Uncommon_Use
5759	5762	Recommended
5763		Uncommon_Use
5764	5777	Recommended
5778		Uncommon_Use
5779	5780	Recommended
5781		Uncommon_Use
5782	5786	Recommended
5787		Uncommon_Use
5788	5795	Recommended
5796		Uncommon_Use
5797	57A7	Recommended
57A8		Uncommon_Use
57A9	57C9	Recommended
57CA		Uncommon_Use
57CB	57D0	Recommended
57D1		Uncommon_Use
57D2	57DA	Recommended
57DB		Uncommon_Use
57DC	5816	Recommended
5817	5818	Uncommon_Use
5819	584F	Recommended
5850		Uncommon_Use
5851	5855	Recommended
5856		Uncommon_Use
5857	585F	Recommended
5860		Uncommon_Use
5861	5865	Recommended
5866	5867	Uncommon_Use
5868	5876	Recommended
5877		Uncommon_Use
5878	5894	Recommended
5895		Uncommon_Use
5896	58A9	Recommended
58AA		Uncommon_Use
58AB	58B5	Recommended
58B6		Uncommon_Use
58B7	58BF	Recommended
58C0		Uncommon_Use
58C1	58C2	Recommended
58C3	58C4	Uncommon_Use
58C5	58CC	Recommended
58CD		Uncommon_Use
58CE	58CF	Recommended
58D0		Uncommon_Use
58D1	58E0	Recommended
58E1		Uncommon_Use
58E2	58E5	Recommended
58E6		Uncommon_Use
58E7	58F4	Recommended
58F5		Uncommon_Use
58F6	5900	Recommended
5901		Uncommon_Use
5902	5904	Recommended
5905		Uncommon_Use
5906	5907	Recommended
5908		Uncommon_Use
5909	5910	Recommended
5911		Uncommon_Use
5912		Recommended
5913		Uncommon_Use
5914	5922	Recommended
5923		Uncommon_Use
5924	5932	Recommended
5933		Uncommon_Use
5934	5935	Recommended
5936		Uncommon_Use
5937	5958	Recommended
5959		Uncommon_Use
595A		Recommended
595B		Uncommon_Use
595C	59B6	Recommended
59B7		Uncommon_Use
59B8	59E6	Recommended
59E7		Uncommon_Use
59E8	5A23	Recommended
5A24		Uncommon_Use
5A25		Recommended
5A26		Uncommon_Use
5A27	5A2B	Recommended
5A2C		Uncommon_Use
5A2D	5A2F	Recommended
5A30		Uncommon_Use
5A31	5A53	Recommended
5A54		Uncommon_Use
5A55	5A58	Recommended
5A59		Uncommon_Use
5A5A	5A6E	Recommended
5A6F		Uncommon_Use
5A70		Recommended
5A71		Uncommon_Use
5A72	5A86	Recommended
5A87		Uncommon_Use
5A88	5A8C	Recommended
5A8D		Uncommon_Use
5A8E	5AAA	Recommended
5AAB		Uncommon_Use
5AAC	5AD2	Recommended
5AD3		Uncommon_Use
5AD4	5AEE	Recommended
5AEF	5AF0	Uncommon_Use
5AF1	5B09	Recommended
5B0A		Uncommon_Use
5B0B	5B0C	Recommended
5B0D		Uncommon_Use
5B0E	5B38	Recommended
5B39		Uncommon_Use
5B3A	5B45	Recommended
5B46		Uncommon_Use
5B47	5B4E	Recommended
5B4F		Uncommon_Use
5B50	5B51	Recommended
5B52		Uncommon_Use
5B53	5B5F	Recommended
5B60	5B61	Uncommon_Use
5B62	5B6E	Recommended
5B6F		Uncommon_Use
5B70	5B78	Recommended
5B79		Uncommon_Use
5B7A	5B7D	Recommended
5B7E		Uncommon_Use
5B7F	5B85	Recommended
5B86		Uncommon_Use
5B87	5B8F	Recommended
5B90		Uncommon_Use
5B91	5BA8	Recommended
5BA9		Uncommon_Use
5BAA	5BB1	Recommended
5BB2		Uncommon_Use
5BB3	5BB6	Recommended
5BB7		Uncommon_Use
5BB8	5BBB	Recommended
5BBC		Uncommon_Use
5BBD	5BC7	Recommended
5BC8		Uncommon_Use
5BC9	5BD9	Recommended
5BDA		Uncommon_Use
5BDB	5BFF	Recommended
5C00		Uncommon_Use
5C01	5C1A	Recommended
5C1B		Uncommon_Use
5C1C	5C22	Recommended
5C23		Uncommon_Use
5C24	5C25	Recommended
5C26		Uncommon_Use
5C27	5C28	Recommended
5C29		Uncommon_Use
5C2A	5C35	Recommended
5C36		Uncommon_Use
5C37	5C59	Recommended
5C5A		Uncommon_Use
5C5B	5C84	Recommended
5C85		Uncommon_Use
5C86	5CB3	Recommended
5CB4		Uncommon_Use
5CB5	5CB8	Recommended
5CB9		Uncommon_Use
5CBA	5CD4	Recommended
5CD5		Uncommon_Use
5CD6	5CDC	Recommended
5CDD		Uncommon_Use
5CDE	5CF4	Recommended
5CF5		Uncommon_Use
5CF6	5D2A	Recommended
5D2B		Uncommon_Use
5D2C	5D2E	Recommended
5D2F		Uncommon_Use
5D30	5D3A	Recommended
5D3B		Uncommon_Use
5D3C	5D52	Recommended
5D53		Uncommon_Use
5D54	5D56	Recommended
5D57		Uncommon_Use
5D58	5D5F	Recommended
5D60		Uncommon_Use
5D61	5D82	Recommended
5D83		Uncommon_Use
5D84	5D95	Recommended
5D96		Uncommon_Use
5D97	5DA2	Recommended
5DA3	5DA4	Uncommon_Use
5DA5	5DAA	Recommended
5DAB		Uncommon_Use
5DAC	5DB2	Recommended
5DB3		Uncommon_Use
5DB4	5DB8	Recommended
5DB9		Uncommon_Use
5DBA	5DC3	Recommended
5DC4		Uncommon_Use
5DC5	5DD6	Recommended
5DD7		Uncommon_Use
5DD8	5DD9	Recommended
5DDA		Uncommon_Use
5DDB		Recommended
5DDC		Uncommon_Use
5DDD	5DF5	Recommended
5DF6		Uncommon_Use
5DF7	5E11	Recommended
5E12		Uncommon_Use
5E13	5E47	Recommended
5E48		Uncommon_Use
5E49	5E50	Recommended
5E51		Uncommon_Use
5E52	5E91	Recommended
5E92		Uncommon_Use
5E93	5EB9	Recommended
5EBA		Uncommon_Use
5EBB	5EBF	Recommended
5EC0		Uncommon_Use
5EC1	5EEA	Recommended
5EEB		Uncommon_Use
5EEC	5EF8	Recommended
5EF9		Uncommon_Use
5EFA	5F0D	Recommended
5F0E		Uncommon_Use
5F0F	5F3A	Recommended
5F3B		Uncommon_Use
5F3C		Recommended
5F3D		Uncommon_Use
5F3E	5F8E	Recommended
5F8F		Uncommon_Use
5F90	5F99	Recommended
5F9A		Uncommon_Use
5F9B	5FA2	Recommended
5FA3	5FA4	Uncommon_Use
5FA5	5FAF	Recommended
5FB0		Uncommon_Use
5FB1	5FC1	Recommended
5FC2		Uncommon_Use
5FC3	5FCD	Recommended
5FCE		Uncommon_Use
5FCF	5FDA	Recommended
5FDB		Uncommon_Use
5FDC	5FE1	Recommended
5FE2		Uncommon_Use
5FE3	5FEB	Recommended
5FEC		Uncommon_Use
5FED	5FFB	Recommended
5FFC		Uncommon_Use
5FFD	6022	Recommended
6023		Uncommon_Use
6024	6055	Recommended
6056		Uncommon_Use
6057	6060	Recommended
6061		Uncommon_Use
6062	6070	Recommended
6071		Uncommon_Use
6072	6073	Recommended
6074		Uncommon_Use
6075	6090	Recommended
6091		Uncommon_Use
6092		Recommended
6093		Uncommon_Use
6094	60A4	Recommended
60A5		Uncommon_Use
60A6	60D1	Recommended
60D2		Uncommon_Use
60D3	60D5	Recommended
60D6		Uncommon_Use
60D7	60DD	Recommended
60DE		Uncommon_Use
60DF	60E4	Recommended
60E5		Uncommon_Use
60E6	60FC	Recommended
60FD		Uncommon_Use
60FE	6101	Recommended
6102		Uncommon_Use
6103	6106	Recommended
6107		Uncommon_Use
6108	6110	Recommended
6111		Uncommon_Use
6112	611D	Recommended
611E		Uncommon_Use
611F	6130	Recommended
6131		Uncommon_Use
6132		Recommended
6133		Uncommon_Use
6134		Recommended
6135		Uncommon_Use
6136	6137	Recommended
6138	6139	Uncommon_Use
613A	615F	Recommended
6160		Uncommon_Use
6161	617A	Recommended
617B		Uncommon_Use
617C	617E	Recommended
617F		Uncommon_Use
6180	6185	Recommended
6186		Uncommon_Use
6187	6196	Recommended
6197		Uncommon_Use
6198	619B	Recommended
619C		Uncommon_Use
619D	61B8	Recommended
61B9		Uncommon_Use
61BA		Recommended
61BB		Uncommon_Use
61BC	61D2	Recommended
61D3		Uncommon_Use
61D4		Recommended
61D5		Uncommon_Use
61D6	61EB	Recommended
61EC		Uncommon_Use
61ED	61EE	Recommended
61EF		Uncommon_Use
61F0	6204	Recommended
6205		Uncommon_Use
6206	6234	Recommended
6235		Uncommon_Use
6236	6238	Recommended
6239		Uncommon_Use
623A	6256	Recommended
6257		Uncommon_Use
6258	628C	Recommended
628D		Uncommon_Use
628E	629C	Recommended
629D		Uncommon_Use
629E	62DD	Recommended
62DE		Uncommon_Use
62DF	62E9	Recommended
62EA		Uncommon_Use
62EB	6309	Recommended
630A		Uncommon_Use
630B	6316	Recommended
6317		Uncommon_Use
6318	6330	Recommended
6331		Uncommon_Use
6332	6336	Recommended
6337		Uncommon_Use
6338	635A	Recommended
635B		Uncommon_Use
635C	638A	Recommended
638B		Uncommon_Use
638C	6392	Recommended
6393		Uncommon_Use
6394	63D0	Recommended
63D1		Uncommon_Use
63D2	643A	Recommended
643B	643C	Uncommon_Use
643D	6448	Recommended
6449		Uncommon_Use
644A	6459	Recommended
645A		Uncommon_Use
645B	647D	Recommended
647E		Uncommon_Use
647F	6485	Recommended
6486		Uncommon_Use
6487	64A0	Recommended
64A1		Uncommon_Use
64A2	64AE	Recommended
64AF		Uncommon_Use
64B0	64B5	Recommended
64B6		Uncommon_Use
64B7	64C7	Recommended
64C8		Uncommon_Use
64C9	64D4	Recommended
64D5		Uncommon_Use
64D6	64ED	Recommended
64EE		Uncommon_Use
64EF	64F4	Recommended
64F5		Uncommon_Use
64F6	64F8	Recommended
64F9		Uncommon_Use
64FA	6501	Recommended
6502		Uncommon_Use
6503	6509	Recommended
650A		Uncommon_Use
650B	651E	Recommended
651F		Uncommon_Use
6520	6527	Recommended
6528		Uncommon_Use
6529	653F	Recommended
6540		Uncommon_Use
6541		Recommended
6542		Uncommon_Use
6543	6559	Recommended
655A		Uncommon_Use
655B	655E	Recommended
655F		Uncommon_Use
6560	657C	Recommended
657D		Uncommon_Use
657E	6589	Recommended
658A		Uncommon_Use
658B	6599	Recommended
659A		Uncommon_Use
659B	65B4	Recommended
65B5		Uncommon_Use
65B6	65BD	Recommended
65BE		Uncommon_Use
65BF	65C7	Recommended
65C8	65C9	Uncommon_Use
65CA	65D0	Recommended
65D1		Uncommon_Use
65D2	65D7	Recommended
65D8		Uncommon_Use
65D9	65DB	Recommended
65DC		Uncommon_Use
65DD	65E3	Recommended
65E4		Uncommon_Use
65E5	65E9	Recommended
65EA		Uncommon_Use
65EB	65F8	Recommended
65F9		Uncommon_Use
65FA	65FD	Recommended
65FE		Uncommon_Use
65FF	6616	Recommended
6617		Uncommon_Use
6618	662B	Recommended
662C		Uncommon_Use
662D	6636	Recommended
6637	6638	Uncommon_Use
6639	6647	Recommended
6648		Uncommon_Use
6649	664C	Recommended
664D		Uncommon_Use
664E	665F	Recommended
6660		Uncommon_Use
6661	6662	Recommended
6663		Uncommon_Use
6664	6691	Recommended
6692		Uncommon_Use
6693	669B	Recommended
669C		Uncommon_Use
669D		Recommended
669E		Uncommon_Use
669F	66AB	Recommended
66AC	66AD	Uncommon_Use
66AE	66CF	Recommended
66D0		Uncommon_Use
66D1	66D2	Recommended
66D3		Uncommon_Use
66D4	66D6	Recommended
66D7		Uncommon_Use
66D8	66DE	Recommended
66DF		Uncommon_Use
66E0	66EE	Recommended
66EF		Uncommon_Use
66F0	6701	Recommended
6702		Uncommon_Use
6703	6706	Recommended
6707		Uncommon_Use
6708	6718	Recommended
6719		Uncommon_Use
671A	6723	Recommended
6724		Uncommon_Use
6725	6728	Recommended
6729		Uncommon_Use
672A	6766	Recommended
6767		Uncommon_Use
6768	6787	Recommended
6788		Uncommon_Use
6789	6795	Recommended
6796		Uncommon_Use
6797	67BC	Recommended
67BD		Uncommon_Use
67BE		Recommended
67BF		Uncommon_Use
67C0	67D4	Recommended
67D5		Uncommon_Use
67D6		Recommended
67D7		Uncommon_Use
67D8	67F8	Recommended
67F9		Uncommon_Use
67FA	6800	Recommended
6801		Uncommon_Use
6802	6814	Recommended
6815		Uncommon_Use
6816	6826	Recommended
6827		Uncommon_Use
6828	682F	Recommended
6830		Uncommon_Use
6831	6857	Recommended
6858		Uncommon_Use
6859		Recommended
685A		Uncommon_Use
685B	685D	Recommended
685E		Uncommon_Use
685F	6879	Recommended
687A		Uncommon_Use
687B	6894	Recommended
6895		Uncommon_Use
6896	6898	Recommended
6899		Uncommon_Use
689A	68A4	Recommended
68A5		Uncommon_Use
68A6	68B7	Recommended
68B8		Uncommon_Use
68B9	68C2	Recommended
68C3		Uncommon_Use
68C4	68D8	Recommended
68D9		Uncommon_Use
68DA	68E1	Recommended
68E2		Uncommon_Use
68E3	68E4	Recommended
68E5		Uncommon_Use
68E6	6908	Recommended
6909		Uncommon_Use
690A	693D	Recommended
693E		Uncommon_Use
693F	694C	Recommended
694D		Uncommon_Use
694E	699E	Recommended
699F		Uncommon_Use
69A0	69A1	Recommended
69A2		Uncommon_Use
69A3	69BF	Recommended
69C0		Uncommon_Use
69C1	69D0	Recommended
69D1	69D2	Uncommon_Use
69D3	69D4	Recommended
69D5	69D7	Uncommon_Use
69D8	6A02	Recommended
6A03		Uncommon_Use
6A04	6A1B	Recommended
6A1C		Uncommon_Use
6A1D	6A23	Recommended
6A24		Uncommon_Use
6A25	6A36	Recommended
6A37		Uncommon_Use
6A38	6A49	Recommended
6A4A		Uncommon_Use
6A4B	6A5B	Recommended
6A5C		Uncommon_Use
6A5D	6A6D	Recommended
6A6E		Uncommon_Use
6A6F		Recommended
6A70		Uncommon_Use
6A71	6A85	Recommended
6A86		Uncommon_Use
6A87	6A89	Recommended
6A8A		Uncommon_Use
6A8B	6A8E	Recommended
6A8F		Uncommon_Use
6A90	6A98	Recommended
6A99		Uncommon_Use
6A9A	6A9C	Recommended
6A9D		Uncommon_Use
6A9E	6AB0	Recommended
6AB1		Uncommon_Use
6AB2	6ABD	Recommended
6ABE		Uncommon_Use
6ABF		Recommended
6AC0		Uncommon_Use
6AC1	6AC3	Recommended
6AC4		Uncommon_Use
6AC5	6AC8	Recommended
6AC9		Uncommon_Use
6ACA	6AD7	Recommended
6AD8		Uncommon_Use
6AD9	6AE8	Recommended
6AE9		Uncommon_Use
6AEA	6B0D	Recommended
6B0E		Uncommon_Use
6B0F	6B1A	Recommended
6B1B		Uncommon_Use
6B1C	6B2D	Recommended
6B2E		Uncommon_Use
6B2F	6B34	Recommended
6B35		Uncommon_Use
6B36	6B3F	Recommended
6B40		Uncommon_Use
6B41	6B56	Recommended
6B57	6B58	Uncommon_Use
6B59	6B5C	Recommended
6B5D		Uncommon_Use
6B5E	6B67	Recommended
6B68		Uncommon_Use
6B69	6B6B	Recommended
6B6C		Uncommon_Use
6B6D		Recommended
6B6E		Uncommon_Use
6B6F	6B70	Recommended
6B71		Uncommon_Use
6B72	6B74	Recommended
6B75		Uncommon_Use
6B76	6B7C	Recommended
6B7D		Uncommon_Use
6B7E	6BB7	Recommended
6BB8		Uncommon_Use
6BB9	6BE8	Recommended
6BE9		Uncommon_Use
6BEA	6BF0	Recommended
6BF1		Uncommon_Use
6BF2	6BF3	Recommended
6BF4		Uncommon_Use
6BF5	6BF9	Recommended
6BFA		Uncommon_Use
6BFB	6C09	Recommended
6C0A		Uncommon_Use
6C0B	6C1B	Recommended
6C1C		Uncommon_Use
6C1D	6C2C	Recommended
6C2D		Uncommon_Use
6C2E	6C3B	Recommended
6C3C		Uncommon_Use
6C3D	6C44	Recommended
6C45		Uncommon_Use
6C46	6C6B	Recommended
6C6C		Uncommon_Use
6C6D		Recommended
6C6E		Uncommon_Use
6C6F	6C9F	Recommended
6CA0		Uncommon_Use
6CA1	6CD7	Recommended
6CD8		Uncommon_Use
6CD9	6CF3	Recommended
6CF4		Uncommon_Use
6CF5	6D01	Recommended
6D02		Uncommon_Use
6D03	6D1B	Recommended
6D1C		Uncommon_Use
6D1D	6D23	Recommended
6D24		Uncommon_Use
6D25	6D70	Recommended
6D71		Uncommon_Use
6D72	6D80	Recommended
6D81		Uncommon_Use
6D82	6D95	Recommended
6D96		Uncommon_Use
6D97	6DAF	Recommended
6DB0	6DB1	Uncommon_Use
6DB2	6DB5	Recommended
6DB6		Uncommon_Use
6DB7	6DFD	Recommended
6DFE	6DFF	Uncommon_Use
6E00		Recommended
6E01	6E02	Uncommon_Use
6E03	6E05	Recommended
6E06		Uncommon_Use
6E07	6E11	Recommended
6E12		Uncommon_Use
6E13	6E17	Recommended
6E18		Uncommon_Use
6E19	6E29	Recommended
6E2A		Uncommon_Use
6E2B	6E4B	Recommended
6E4C		Uncommon_Use
6E4D	6E6B	Recommended
6E6C		Uncommon_Use
6E6D	6E7A	Recommended
6E7B	6E7D	Uncommon_Use
6E7E	6E8A	Recommended
6E8B		Uncommon_Use
6E8C	6E94	Recommended
6E95		Uncommon_Use
6E96	6EDA	Recommended
6EDB		Uncommon_Use
6EDC	6EE2	Recommended
6EE3		Uncommon_Use
6EE4	6F03	Recommended
6F04		Uncommon_Use
6F05	6F0A	Recommended
6F0B		Uncommon_Use
6F0C	6F41	Recommended
6F42		Uncommon_Use
6F43	6F47	Recommended
6F48		Uncommon_Use
6F49		Recommended
6F4A		Uncommon_Use
6F4B	6F78	Recommended
6F79		Uncommon_Use
6F7A	6F97	Recommended
6F98		Uncommon_Use
6F99		Recommended
6F9A		Uncommon_Use
6F9B	6F9E	Recommended
6F9F		Uncommon_Use
6FA0	6FB6	Recommended
6FB7		Uncommon_Use
6FB8	6FC4	Recommended
6FC5		Uncommon_Use
6FC6	6FCF	Recommended
6FD0		Uncommon_Use
6FD1	6FD2	Recommended
6FD3		Uncommon_Use
6FD4	6FF4	Recommended
6FF5		Uncommon_Use
6FF6	6FFC	Recommended
6FFD		Uncommon_Use
6FFE	700F	Recommended
7010		Uncommon_Use
7011	7012	Recommended
7013		Uncommon_Use
7014	7046	Recommended
7047		Uncommon_Use
7048	704A	Recommended
704B		Uncommon_Use
704C	704D	Recommended
704E		Uncommon_Use
704F	7071	Recommended
7072	7073	Uncommon_Use
7074	707A	Recommended
707B		Uncommon_Use
707C	7080	Recommended
7081		Uncommon_Use
7082	708C	Recommended
708D		Uncommon_Use
708E	7096	Recommended
7097		Uncommon_Use
7098	709A	Recommended
709B		Uncommon_Use
709C	70A9	Recommended
70AA		Uncommon_Use
70AB	70B1	Recommended
70B2		Uncommon_Use
70B3	70B5	Recommended
70B6		Uncommon_Use
70B7	70D4	Recommended
70D5		Uncommon_Use
70D6	70FD	Recommended
70FE		Uncommon_Use
70FF	7107	Recommended
7108		Uncommon_Use
7109	7123	Recommended
7124		Uncommon_Use
7125	7132	Recommended
7133	7134	Uncommon_Use
7135	7156	Recommended
7157		Uncommon_Use
7158	716A	Recommended
716B		Uncommon_Use
716C		Recommended
716D		Uncommon_Use
716E	718C	Recommended
718D		Uncommon_Use
718E	7195	Recommended
7196		Uncommon_Use
7197	71A5	Recommended
71A6		Uncommon_Use
71A7	71AA	Recommended
71AB		Uncommon_Use
71AC	71B5	Recommended
71B6		Uncommon_Use
71B7	71CB	Recommended
71CC		Uncommon_Use
71CD	71D2	Recommended
71D3		Uncommon_Use
71D4	71F2	Recommended
71F3		Uncommon_Use
71F4	71F9	Recommended
71FA		Uncommon_Use
71FB	720A	Recommended
720B		Uncommon_Use
720C	7210	Recommended
7211		Uncommon_Use
7212	7214	Recommended
7215		Uncommon_Use
7216		Recommended
7217		Uncommon_Use
7218	721F	Recommended
7220		Uncommon_Use
7221	7223	Recommended
7224	7225	Uncommon_Use
7226	722E	Recommended
722F		Uncommon_Use
7230	7233	Recommended
7234		Uncommon_Use
7235	7244	Recommended
7245		Uncommon_Use
7246	724D	Recommended
724E		Uncommon_Use
724F		Recommended
7250		Uncommon_Use
7251	7254	Recommended
7255		Uncommon_Use
7256	72AA	Recommended
72AB		Uncommon_Use
72AC	72BD	Recommended
72BE		Uncommon_Use
72BF	7301	Recommended
7302		Uncommon_Use
7303	730F	Recommended
7310		Uncommon_Use
7311	7327	Recommended
7328		Uncommon_Use
7329	7352	Recommended
7353		Uncommon_Use
7354	739B	Recommended
739C		Uncommon_Use
739D	73C0	Recommended
73C1		Uncommon_Use
73C2	73F2	Recommended
73F3		Uncommon_Use
73F4	73FA	Recommended
73FB		Uncommon_Use
73FC	7417	Recommended
7418		Uncommon_Use
7419	7438	Recommended
7439		Uncommon_Use
743A	743D	Recommended
743E		Uncommon_Use
743F	7446	Recommended
7447		Uncommon_Use
7448		Recommended
7449		Uncommon_Use
744A	7457	Recommended
7458		Uncommon_Use
7459	747A	Recommended
747B		Uncommon_Use
747C	7483	Recommended
7484		Uncommon_Use
7485	7495	Recommended
7496		Uncommon_Use
7497	749C	Recommended
749D		Uncommon_Use
749E	74C6	Recommended
74C7		Uncommon_Use
74C8		Recommended
74C9		Uncommon_Use
74CA	74CB	Recommended
74CC		Uncommon_Use
74CD	74EA	Recommended
74EB		Uncommon_Use
74EC	751F	Recommended
7520		Uncommon_Use
7521	7540	Recommended
7541		Uncommon_Use
7542	7551	Recommended
7552		Uncommon_Use
7553	7554	Recommended
7555		Uncommon_Use
7556	755D	Recommended
755E		Uncommon_Use
755F	7560	Recommended
7561		Uncommon_Use
7562	7570	Recommended
7571		Uncommon_Use
7572	757A	Recommended
757B		Uncommon_Use
757C	7584	Recommended
7585		Uncommon_Use
7586	75A8	Recommended
75A9		Uncommon_Use
75AA	75B6	Recommended
75B7		Uncommon_Use
75B8	75DB	Recommended
75DC		Uncommon_Use
75DD	75ED	Recommended
75EE		Uncommon_Use
75EF	762B	Recommended
762C		Uncommon_Use
762D	7643	Recommended
7644	7645	Uncommon_Use
7646	7650	Recommended
7651		Uncommon_Use
7652	7654	Recommended
7655		Uncommon_Use
7656	7672	Recommended
7673		Uncommon_Use
7674	768C	Recommended
768D		Uncommon_Use
768E	76A0	Recommended
76A1	76A2	Uncommon_Use
76A3	76A4	Recommended
76A5		Uncommon_Use
76A6	76A7	Recommended
76A8		Uncommon_Use
76A9	76B2	Recommended
76B3		Uncommon_Use
76B4	76B5	Recommended
76B6		Uncommon_Use
76B7	76C0	Recommended
76C1		Uncommon_Use
76C2	76CA	Recommended
76CB		Uncommon_Use
76CC	76D8	Recommended
76D9		Uncommon_Use
76DA	76EA	Recommended
76EB		Uncommon_Use
76EC	76FF	Recommended
7700		Uncommon_Use
7701		Recommended
7702		Uncommon_Use
7703	770D	Recommended
770E		Uncommon_Use
770F	7720	Recommended
7721		Uncommon_Use
7722	772A	Recommended
772B		Uncommon_Use
772C	773E	Recommended
773F		Uncommon_Use
7740	7741	Recommended
7742		Uncommon_Use
7743	7763	Recommended
7764		Uncommon_Use
7765	7795	Recommended
7796		Uncommon_Use
7797	77A3	Recommended
77A4		Uncommon_Use
77A5	77BD	Recommended
77BE		Uncommon_Use
77BF	77C0	Recommended
77C1		Uncommon_Use
77C2	77D1	Recommended
77D2		Uncommon_Use
77D3	77DC	Recommended
77DD		Uncommon_Use
77DE	77E3	Recommended
77E4		Uncommon_Use
77E5		Recommended
77E6		Uncommon_Use
77E7	77F3	Recommended
77F4	77F5	Uncommon_Use
77F6	7823	Recommended
7824		Uncommon_Use
7825	7835	Recommended
7836		Uncommon_Use
7837	7841	Recommended
7842		Uncommon_Use
7843	7845	Recommended
7846		Uncommon_Use
7847	784A	Recommended
784B		Uncommon_Use
784C	7875	Recommended
7876		Uncommon_Use
7877	7887	Recommended
7888		Uncommon_Use
7889	78C1	Recommended
78C2		Uncommon_Use
78C3	78C6	Recommended
78C7		Uncommon_Use
78C8	78D1	Recommended
78D2		Uncommon_Use
78D3	78EF	Recommended
78F0		Uncommon_Use
78F1	78F7	Recommended
78F8		Uncommon_Use
78F9	78FF	Recommended
7900		Uncommon_Use
7901	7907	Recommended
7908		Uncommon_Use
7909	790C	Recommended
790D		Uncommon_Use
790E	7914	Recommended
7915		Uncommon_Use
7916	791E	Recommended
791F	7920	Uncommon_Use
7921	7931	Recommended
7932		Uncommon_Use
7933	7935	Recommended
7936		Uncommon_Use
7937	7958	Recommended
7959		Uncommon_Use
795A	796B	Recommended
796C		Uncommon_Use
796D		Recommended
796E		Uncommon_Use
796F	7974	Recommended
7975	7976	Uncommon_Use
7977	7985	Recommended
7986	7987	Uncommon_Use
7988	799D	Recommended
799E		Uncommon_Use
799F	79A8	Recommended
79A9		Uncommon_Use
79AA	79BB	Recommended
79BC		Uncommon_Use
79BD	79C3	Recommended
79C4		Uncommon_Use
79C5	79C6	Recommended
79C7		Uncommon_Use
79C8	79CB	Recommended
79CC		Uncommon_Use
79CD	79D3	Recommended
79D4		Uncommon_Use
79D5	79D6	Recommended
79D7		Uncommon_Use
79D8	7A00	Recommended
7A01		Uncommon_Use
7A02	7A06	Recommended
7A07		Uncommon_Use
7A08		Recommended
7A09		Uncommon_Use
7A0A	7A2B	Recommended
7A2C		Uncommon_Use
7A2D	7A37	Recommended
7A38		Uncommon_Use
7A39		Recommended
7A3A		Uncommon_Use
7A3B	7A63	Recommended
7A64		Uncommon_Use
7A65	7A69	Recommended
7A6A		Uncommon_Use
7A6B	7A6E	Recommended
7A6F		Uncommon_Use
7A70	7A81	Recommended
7A82		Uncommon_Use
7A83	7A99	Recommended
7A9A	7A9B	Uncommon_Use
7A9C	7AB8	Recommended
7AB9		Uncommon_Use
7ABA		Recommended
7ABB	7ABD	Uncommon_Use
7ABE	7AC1	Recommended
7AC2		Uncommon_Use
7AC3	7AC5	Recommended
7AC6		Uncommon_Use
7AC7	7AE8	Recommended
7AE9		Uncommon_Use
7AEA	7AF4	Recommended
7AF5		Uncommon_Use
7AF6	7AFB	Recommended
7AFC		Uncommon_Use
7AFD	7B06	Recommended
7B07		Uncommon_Use
7B08	7B1E	Recommended
7B1F		Uncommon_Use
7B20	7B26	Recommended
7B27		Uncommon_Use
7B28		Recommended
7B29		Uncommon_Use
7B2A	7B41	Recommended
7B42		Uncommon_Use
7B43	7B52	Recommended
7B53		Uncommon_Use
7B54	7BA2	Recommended
7BA3		Uncommon_Use
7BA4		Recommended
7BA5		Uncommon_Use
7BA6	7BAF	Recommended
7BB0		Uncommon_Use
7BB1		Recommended
7BB2		Uncommon_Use
7BB3	7BF9	Recommended
7BFA		Uncommon_Use
7BFB	7C1A	Recommended
7C1B		Uncommon_Use
7C1C	7C2D	Recommended
7C2E	7C2F	Uncommon_Use
7C30	7C51	Recommended
7C52		Uncommon_Use
7C53	7C54	Recommended
7C55		Uncommon_Use
7C56	7C5C	Recommended
7C5D		Uncommon_Use
7C5E	7C75	Recommended
7C76		Uncommon_Use
7C77	7C86	Recommended
7C87		Uncommon_Use
7C88	7C92	Recommended
7C93		Uncommon_Use
7C94	7C99	Recommended
7C9A		Uncommon_Use
7C9B	7CAB	Recommended
7CAC		Uncommon_Use
7CAD	7CD2	Recommended
7CD3		Uncommon_Use
7CD4	7CD9	Recommended
7CDA	7CDB	Uncommon_Use
7CDC	7CE0	Recommended
7CE1		Uncommon_Use
7CE2		Recommended
7CE3		Uncommon_Use
7CE4		Recommended
7CE5	7CE6	Uncommon_Use
7CE7	7CFB	Recommended
7CFC		Uncommon_Use
7CFD	7CFE	Recommended
7CFF		Uncommon_Use
7D00	7D22	Recommended
7D23		Uncommon_Use
7D24	7D29	Recommended
7D2A		Uncommon_Use
7D2B	7D2C	Recommended
7D2D		Uncommon_Use
7D2E	7D47	Recommended
7D48		Uncommon_Use
7D49	7D4C	Recommended
7D4D		Uncommon_Use
7D4E	7D59	Recommended
7D5A		Uncommon_Use
7D5B	7D63	Recommended
7D64		Uncommon_Use
7D65	7D77	Recommended
7D78		Uncommon_Use
7D79	7D81	Recommended
7D82		Uncommon_Use
7D83	7D94	Recommended
7D95		Uncommon_Use
7D96	7D97	Recommended
7D98		Uncommon_Use
7D99	7DA3	Recommended
7DA4		Uncommon_Use
7DA5	7DA7	Recommended
7DA8		Uncommon_Use
7DA9	7DCC	Recommended
7DCD		Uncommon_Use
7DCE	7DD2	Recommended
7DD3		Uncommon_Use
7DD4	7DE4	Recommended
7DE5		Uncommon_Use
7DE6	7DEA	Recommended
7DEB		Uncommon_Use
7DEC	7DFC	Recommended
7DFD	7DFF	Uncommon_Use
7E00	7E17	Recommended
7E18		Uncommon_Use
7E19	7E5A	Recommended
7E5B		Uncommon_Use
7E5C	7E63	Recommended
7E64		Uncommon_Use
7E65	7E9C	Recommended
7E9D		Uncommon_Use
7E9E	7F3A	Recommended
7F3B	7F3C	Uncommon_Use
7F3D	7F40	Recommended
7F41		Uncommon_Use
7F42	7F45	Recommended
7F46		Uncommon_Use
7F47	7F58	Recommended
7F59		Uncommon_Use
7F5A	7F83	Recommended
7F84		Uncommon_Use
7F85	7F8F	Recommended
7F90		Uncommon_Use
7F91	7F96	Recommended
7F97		Uncommon_Use
7F98		Recommended
7F99		Uncommon_Use
7F9A	7FB3	Recommended
7FB4		Uncommon_Use
7FB5	7FD5	Recommended
7FD6		Uncommon_Use
7FD7	7FDC	Recommended
7FDD		Uncommon_Use
7FDE	7FE3	Recommended
7FE4		Uncommon_Use
7FE5	8009	Recommended
800A		Uncommon_Use
800B	802E	Recommended
802F		Uncommon_Use
8030	803B	Recommended
803C		Uncommon_Use
803D	803F	Recommended
8040		Uncommon_Use
8041	8065	Recommended
8066		Uncommon_Use
8067	8087	Recommended
8088		Uncommon_Use
8089	808D	Recommended
808E		Uncommon_Use
808F	8093	Recommended
8094		Uncommon_Use
8095	80A5	Recommended
80A6	80A8	Uncommon_Use
80A9	80B2	Recommended
80B3		Uncommon_Use
80B4	80B8	Recommended
80B9		Uncommon_Use
80BA	80DE	Recommended
80DF		Uncommon_Use
80E0	8102	Recommended
8103	8104	Uncommon_Use
8105	8133	Recommended
8134	8135	Uncommon_Use
8136	8183	Recommended
8184		Uncommon_Use
8185	818F	Recommended
8190		Uncommon_Use
8191	8195	Recommended
8196		Uncommon_Use
8197	81CA	Recommended
81CB		Uncommon_Use
81CC	81E3	Recommended
81E4		Uncommon_Use
81E5	81EE	Recommended
81EF	81F0	Uncommon_Use
81F1	8212	Recommended
8213		Uncommon_Use
8214	8223	Recommended
8224		Uncommon_Use
8225	8240	Recommended
8241		Uncommon_Use
8242	8264	Recommended
8265		Uncommon_Use
8266	828B	Recommended
828C		Uncommon_Use
828D	82B1	Recommended
82B2		Uncommon_Use
82B3	82E1	Recommended
82E2		Uncommon_Use
82E3	82FB	Recommended
82FC		Uncommon_Use
82FD	8309	Recommended
830A		Uncommon_Use
830B	830F	Recommended
8310		Uncommon_Use
8311	832F	Recommended
8330		Uncommon_Use
8331	8354	Recommended
8355		Uncommon_Use
8356	83BD	Recommended
83BE		Uncommon_Use
83BF	83E5	Recommended
83E6		Uncommon_Use
83E7	83EC	Recommended
83ED		Uncommon_Use
83EE	8413	Recommended
8414		Uncommon_Use
8415		Recommended
8416	8417	Uncommon_Use
8418	841E	Recommended
841F		Uncommon_Use
8420	8457	Recommended
8458		Uncommon_Use
8459	8482	Recommended
8483		Uncommon_Use
8484	8494	Recommended
8495		Uncommon_Use
8496	84B6	Recommended
84B7		Uncommon_Use
84B8	84C2	Recommended
84C3		Uncommon_Use
84C4	84EC	Recommended
84ED		Uncommon_Use
84EE	8504	Recommended
8505		Uncommon_Use
8506	850F	Recommended
8510		Uncommon_Use
8511	8531	Recommended
8532	8533	Uncommon_Use
8534	854B	Recommended
854C		Uncommon_Use
854D	854F	Recommended
8550		Uncommon_Use
8551	857E	Recommended
857F		Uncommon_Use
8580	8592	Recommended
8593		Uncommon_Use
8594	85B1	Recommended
85B2		Uncommon_Use
85B3	85BA	Recommended
85BB		Uncommon_Use
85BC	85CB	Recommended
85CC		Uncommon_Use
85CD	85ED	Recommended
85EE		Uncommon_Use
85EF	85F2	Recommended
85F3		Uncommon_Use
85F4	85FB	Recommended
85FC		Uncommon_Use
85FD	8602	Recommended
8603		Uncommon_Use
8604	860C	Recommended
860D	860E	Uncommon_Use
860F		Recommended
8610		Uncommon_Use
8611	8614	Recommended
8615		Uncommon_Use
8616	861C	Recommended
861D		Uncommon_Use
861E	8636	Recommended
8637		Uncommon_Use
8638	8656	Recommended
8657		Uncommon_Use
8658	8674	Recommended
8675		Uncommon_Use
8676	8688	Recommended
8689		Uncommon_Use
868A	8691	Recommended
8692		Uncommon_Use
8693	869F	Recommended
86A0		Uncommon_Use
86A1	86A5	Recommended
86A6		Uncommon_Use
86A7	86D4	Recommended
86D5		Uncommon_Use
86D6	86DF	Recommended
86E0		Uncommon_Use
86E1	86E6	Recommended
86E7		Uncommon_Use
86E8	86FC	Recommended
86FD		Uncommon_Use
86FE	871C	Recommended
871D		Uncommon_Use
871E	872E	Recommended
872F		Uncommon_Use
8730	873C	Recommended
873D		Uncommon_Use
873E	8744	Recommended
8745		Uncommon_Use
8746	8770	Recommended
8771		Uncommon_Use
8772	878D	Recommended
878E		Uncommon_Use
878F	8798	Recommended
8799		Uncommon_Use
879A	87D9	Recommended
87DA		Uncommon_Use
87DB	87EF	Recommended
87F0		Uncommon_Use
87F1	8806	Recommended
8807		Uncommon_Use
8808	8811	Recommended
8812		Uncommon_Use
8813	882C	Recommended
882D		Uncommon_Use
882E	8839	Recommended
883A		Uncommon_Use
883B	8846	Recommended
8847		Uncommon_Use
8848	8857	Recommended
8858		Uncommon_Use
8859	885B	Recommended
885C		Uncommon_Use
885D	885E	Recommended
885F		Uncommon_Use
8860	8879	Recommended
887A		Uncommon_Use
887B	88E5	Recommended
88E6		Uncommon_Use
88E7	88E8	Recommended
88E9		Uncommon_Use
88EA	88EC	Recommended
88ED		Uncommon_Use
88EE	8902	Recommended
8903		Uncommon_Use
8904	890E	Recommended
890F		Uncommon_Use
8910	8923	Recommended
8924		Uncommon_Use
8925	8964	Recommended
8965		Uncommon_Use
8966	8974	Recommended
8975		Uncommon_Use
8976	897C	Recommended
897D		Uncommon_Use
897E	898C	Recommended
898D		Uncommon_Use
898E	898F	Recommended
8990		Uncommon_Use
8991	8993	Recommended
8994		Uncommon_Use
8995	8998	Recommended
8999		Uncommon_Use
899A	89AF	Recommended
89B0		Uncommon_Use
89B1	89B3	Recommended
89B4		Uncommon_Use
89B5	89BA	Recommended
89BB	89BC	Uncommon_Use
89BD	89ED	Recommended
89EE		Uncommon_Use
89EF	89F4	Recommended
89F5		Uncommon_Use
89F6	89F8	Recommended
89F9		Uncommon_Use
89FA	89FC	Recommended
89FD		Uncommon_Use
89FE	8A04	Recommended
8A05	8A06	Uncommon_Use
8A07	8A13	Recommended
8A14		Uncommon_Use
8A15	8A18	Recommended
8A19		Uncommon_Use
8A1A	8A1F	Recommended
8A20	8A21	Uncommon_Use
8A22	8A2A	Recommended
8A2B		Uncommon_Use
8A2C	8A3C	Recommended
8A3D		Uncommon_Use
8A3E	8A4A	Recommended
8A4B		Uncommon_Use
8A4C	8A63	Recommended
8A64		Uncommon_Use
8A65	8A77	Recommended
8A78		Uncommon_Use
8A79	8A7C	Recommended
8A7D		Uncommon_Use
8A7E	8A87	Recommended
8A88		Uncommon_Use
8A89	8A9E	Recommended
8A9F		Uncommon_Use
8AA0	8AAE	Recommended
8AAF		Uncommon_Use
8AB0	8AB6	Recommended
8AB7		Uncommon_Use
8AB8	8ACF	Recommended
8AD0		Uncommon_Use
8AD1	8AEB	Recommended
8AEC		Uncommon_Use
8AED	8B28	Recommended
8B29		Uncommon_Use
8B2A	8B31	Recommended
8B32		Uncommon_Use
8B33	8B37	Recommended
8B38		Uncommon_Use
8B39	8B3E	Recommended
8B3F		Uncommon_Use
8B40	8B60	Recommended
8B61	8B62	Uncommon_Use
8B63	8B68	Recommended
8B69		Uncommon_Use
8B6A	8B74	Recommended
8B75		Uncommon_Use
8B76	8B7B	Recommended
8B7C		Uncommon_Use
8B7D	8B80	Recommended
8B81		Uncommon_Use
8B82	8B86	Recommended
8B87		Uncommon_Use
8B88	8B8C	Recommended
8B8D		Uncommon_Use
8B8E		Recommended
8B8F		Uncommon_Use
8B90	8B9A	Recommended
8B9B		Uncommon_Use
8B9C	8C37	Recommended
8C38		Uncommon_Use
8C39	8C3F	Recommended
8C40		Uncommon_Use
8C41	8C43	Recommended
8C44		Uncommon_Use
8C45	8C50	Recommended
8C51	8C53	Uncommon_Use
8C54	8C57	Recommended
8C58		Uncommon_Use
8C59	8C73	Recommended
8C74		Uncommon_Use
8C75	8C7E	Recommended
8C7F		Uncommon_Use
8C80	8C82	Recommended
8C83		Uncommon_Use
8C84	8C86	Recommended
8C87		Uncommon_Use
8C88	8C8A	Recommended
8C8B		Uncommon_Use
8C8C	8C9A	Recommended
8C9B		Uncommon_Use
8C9C	8CA5	Recommended
8CA6		Uncommon_Use
8CA7	8CCA	Recommended
8CCB		Uncommon_Use
8CCC	8CD5	Recommended
8CD6		Uncommon_Use
8CD7		Recommended
8CD8		Uncommon_Use
8CD9	8CE8	Recommended
8CE9		Uncommon_Use
8CEA	8CF6	Recommended
8CF7		Uncommon_Use
8CF8	8D00	Recommended
8D01		Uncommon_Use
8D02	8D10	Recommended
8D11	8D12	Uncommon_Use
8D13	8D7B	Recommended
8D7C		Uncommon_Use
8D7D	8DA5	Recommended
8DA6		Uncommon_Use
8DA7	8DBF	Recommended
8DC0		Uncommon_Use
8DC1	8DE4	Recommended
8DE5		Uncommon_Use
8DE6	8E00	Recommended
8E01		Uncommon_Use
8E02	8E0A	Recommended
8E0B		Uncommon_Use
8E0C	8E31	Recommended
8E32		Uncommon_Use
8E33	8E45	Recommended
8E46		Uncommon_Use
8E47	8E4E	Recommended
8E4F		Uncommon_Use
8E50	8E6D	Recommended
8E6E		Uncommon_Use
8E6F	8E74	Recommended
8E75		Uncommon_Use
8E76		Recommended
8E77		Uncommon_Use
8E78		Recommended
8E79		Uncommon_Use
8E7A	8E9A	Recommended
8E9B		Uncommon_Use
8E9C	8EA1	Recommended
8EA2		Uncommon_Use
8EA3	8EB2	Recommended
8EB3		Uncommon_Use
8EB4	8EB5	Recommended
8EB6	8EB7	Uncommon_Use
8EB8	8EC0	Recommended
8EC1		Uncommon_Use
8EC2	8EC3	Recommended
8EC4		Uncommon_Use
8EC5	8ED8	Recommended
8ED9		Uncommon_Use
8EDA	8EEF	Recommended
8EF0		Uncommon_Use
8EF1	8F0E	Recommended
8F0F		Uncommon_Use
8F10	8F2C	Recommended
8F2D		Uncommon_Use
8F2E	8F39	Recommended
8F3A		Uncommon_Use
8F3B	8F40	Recommended
8F41		Uncommon_Use
8F42	8F9C	Recommended
8F9D		Uncommon_Use
8F9E	8FA3	Recommended
8FA4		Uncommon_Use
8FA5	8FB2	Recommended
8FB3		Uncommon_Use
8FB4	8FC2	Recommended
8FC3		Uncommon_Use
8FC4	8FC9	Recommended
8FCA		Uncommon_Use
8FCB	8FE6	Recommended
8FE7		Uncommon_Use
8FE8	9029	Recommended
902A		Uncommon_Use
902B		Recommended
902C		Uncommon_Use
902D	9036	Recommended
9037		Uncommon_Use
9038	903F	Recommended
9040		Uncommon_Use
9041	9045	Recommended
9046		Uncommon_Use
9047	90AA	Recommended
90AB		Uncommon_Use
90AC	90CB	Recommended
90CC	90CD	Uncommon_Use
90CE	90D1	Recommended
90D2		Uncommon_Use
90D3	90F5	Recommended
90F6		Uncommon_Use
90F7	9109	Recommended
910A		Uncommon_Use
910B	913B	Recommended
913C	913D	Uncommon_Use
913E	9158	Recommended
9159		Uncommon_Use
915A	917A	Recommended
917B		Uncommon_Use
917C	9194	Recommended
9195		Uncommon_Use
9196	9197	Recommended
9198		Uncommon_Use
9199	91A8	Recommended
91A9		Uncommon_Use
91AA	91BE	Recommended
91BF		Uncommon_Use
91C0	91C3	Recommended
91C4		Uncommon_Use
91C5	91DF	Recommended
91E0		Uncommon_Use
91E1	91EE	Recommended
91EF		Uncommon_Use
91F0	9212	Recommended
9213		Uncommon_Use
9214	921E	Recommended
921F		Uncommon_Use
9220	9221	Recommended
9222		Uncommon_Use
9223	9242	Recommended
9243		Uncommon_Use
9244	9268	Recommended
9269	926A	Uncommon_Use
926B	9280	Recommended
9281		Uncommon_Use
9282	9283	Recommended
9284		Uncommon_Use
9285	929D	Recommended
929E		Uncommon_Use
929F	92BC	Recommended
92BD		Uncommon_Use
92BE	92D3	Recommended
92D4		Uncommon_Use
92D5	92DA	Recommended
92DB		Uncommon_Use
92DC	92E1	Recommended
92E2		Uncommon_Use
92E3	931B	Recommended
931C		Uncommon_Use
931D	932F	Recommended
9330	9331	Uncommon_Use
9332	9361	Recommended
9362		Uncommon_Use
9363	9367	Recommended
9368		Uncommon_Use
9369	936A	Recommended
936B		Uncommon_Use
936C	936E	Recommended
936F		Uncommon_Use
9370	9372	Recommended
9373		Uncommon_Use
9374	9377	Recommended
9378		Uncommon_Use
9379	937E	Recommended
937F		Uncommon_Use
9380		Recommended
9381		Uncommon_Use
9382	938A	Recommended
938B		Uncommon_Use
938C	939B	Recommended
939C		Uncommon_Use
939D	939F	Recommended
93A0		Uncommon_Use
93A1	93AA	Recommended
93AB		Uncommon_Use
93AC	93BA	Recommended
93BB		Uncommon_Use
93BC	93DF	Recommended
93E0		Uncommon_Use
93E1	93F2	Recommended
93F3		Uncommon_Use
93F4	9401	Recommended
9402		Uncommon_Use
9403	9416	Recommended
9417		Uncommon_Use
9418	941B	Recommended
941C		Uncommon_Use
941D		Recommended
941E	941F	Uncommon_Use
9420	9423	Recommended
9424		Uncommon_Use
9425	9442	Recommended
9443		Uncommon_Use
9444	944D	Recommended
944E		Uncommon_Use
944F	946B	Recommended
946C		Uncommon_Use
946D	947A	Recommended
947B		Uncommon_Use
947C	9577	Recommended
9578	9579	Uncommon_Use
957A	957D	Recommended
957E		Uncommon_Use
957F	9584	Recommended
9585		Uncommon_Use
9586	9596	Recommended
9597		Uncommon_Use
9598	95B2	Recommended
95B3	95B4	Uncommon_Use
95B5	95B7	Recommended
95B8		Uncommon_Use
95B9	95C0	Recommended
95C1		Uncommon_Use
95C2	95D8	Recommended
95D9		Uncommon_Use
95DA	95DC	Recommended
95DD		Uncommon_Use
95DE	9624	Recommended
9625	9626	Uncommon_Use
9627	9628	Recommended
9629		Uncommon_Use
962A	963D	Recommended
963E		Uncommon_Use
963F	9655	Recommended
9656	9657	Uncommon_Use
9658	9678	Recommended
9679		Uncommon_Use
967A		Recommended
967B		Uncommon_Use
967C	967E	Recommended
967F		Uncommon_Use
9680		Recommended
9681	9682	Uncommon_Use
9683	968B	Recommended
968C		Uncommon_Use
968D	9695	Recommended
9696		Uncommon_Use
9697	9699	Recommended
969A		Uncommon_Use
969B	969C	Recommended
969D		Uncommon_Use
969E		Recommended
969F		Uncommon_Use
96A0	96AA	Recommended
96AB		Uncommon_Use
96AC	96AE	Recommended
96AF		Uncommon_Use
96B0	96B4	Recommended
96B5		Uncommon_Use
96B6	96E3	Recommended
96E4		Uncommon_Use
96E5		Recommended
96E6	96E7	Uncommon_Use
96E8	96FB	Recommended
96FC		Uncommon_Use
96FD	9713	Recommended
9714		Uncommon_Use
9715	9716	Recommended
9717		Uncommon_Use
9718	9719	Recommended
971A	971B	Uncommon_Use
971C	9732	Recommended
9733	9734	Uncommon_Use
9735	9736	Recommended
9737		Uncommon_Use
9738	973F	Recommended
9740	9741	Uncommon_Use
9742	974C	Recommended
974D		Uncommon_Use
974E	9756	Recommended
9757		Uncommon_Use
9758	9762	Recommended
9763		Uncommon_Use
9764	9774	Recommended
9775		Uncommon_Use
9776	9786	Recommended
9787		Uncommon_Use
9788		Recommended
9789		Uncommon_Use
978A	979A	Recommended
979B		Uncommon_Use
979C	97A8	Recommended
97A9		Uncommon_Use
97AA	97AF	Recommended
97B0	97B1	Uncommon_Use
97B2	97B4	Recommended
97B5		Uncommon_Use
97B6	97BD	Recommended
97BE		Uncommon_Use
97BF		Recommended
97C0		Uncommon_Use
97C1	97D1	Recommended
97D2		Uncommon_Use
97D3	97FB	Recommended
97FC		Uncommon_Use
97FD	981E	Recommended
981F		Uncommon_Use
9820	9824	Recommended
9825		Uncommon_Use
9826	9829	Recommended
982A		Uncommon_Use
982B	9832	Recommended
9833		Uncommon_Use
9834	9839	Recommended
983A		Uncommon_Use
983B	983D	Recommended
983E		Uncommon_Use
983F	9841	Recommended
9842		Uncommon_Use
9843	9846	Recommended
9847		Uncommon_Use
9848	9855	Recommended
9856		Uncommon_Use
9857	9865	Recommended
9866		Uncommon_Use
9867		Recommended
9868		Uncommon_Use
9869	98B6	Recommended
98B7		Uncommon_Use
98B8	98C9	Recommended
98CA		Uncommon_Use
98CB	98E3	Recommended
98E4		Uncommon_Use
98E5	98EB	Recommended
98EC		Uncommon_Use
98ED	98F0	Recommended
98F1		Uncommon_Use
98F2	98F7	Recommended
98F8		Uncommon_Use
98F9	98FA	Recommended
98FB		Uncommon_Use
98FC	9918	Recommended
9919		Uncommon_Use
991A	993A	Recommended
993B		Uncommon_Use
993C	9943	Recommended
9944		Uncommon_Use
9945	9959	Recommended
995A		Uncommon_Use
995B	995C	Recommended
995D		Uncommon_Use
995E	99BE	Recommended
99BF		Uncommon_Use
99C0	99DF	Recommended
99E0		Uncommon_Use
99E1	99E5	Recommended
99E6		Uncommon_Use
99E7	99EA	Recommended
99EB		Uncommon_Use
99EC	99F4	Recommended
99F5		Uncommon_Use
99F6	9A0F	Recommended
9A10		Uncommon_Use
9A11	9A16	Recommended
9A17	9A18	Uncommon_Use
9A19	9A3A	Recommended
9A3B		Uncommon_Use
9A3C	9A50	Recommended
9A51		Uncommon_Use
9A52	9A57	Recommended
9A58		Uncommon_Use
9A59	9A5C	Recommended
9A5D		Uncommon_Use
9A5E	9A62	Recommended
9A63		Uncommon_Use
9A64	9AA8	Recommended
9AA9		Uncommon_Use
9AAA	9ABC	Recommended
9ABD		Uncommon_Use
9ABE	9AC7	Recommended
9AC8		Uncommon_Use
9AC9	9AD6	Recommended
9AD7		Uncommon_Use
9AD8	9ADF	Recommended
9AE0		Uncommon_Use
9AE1	9AE3	Recommended
9AE4		Uncommon_Use
9AE5	9AE7	Recommended
9AE8	9AE9	Uncommon_Use
9AEA	9AEF	Recommended
9AF0		Uncommon_Use
9AF1	9AFF	Recommended
9B00		Uncommon_Use
9B01		Recommended
9B02		Uncommon_Use
9B03	9B08	Recommended
9B09		Uncommon_Use
9B0A	9B13	Recommended
9B14		Uncommon_Use
9B15	9B1A	Recommended
9B1B		Uncommon_Use
9B1C	9B33	Recommended
9B34		Uncommon_Use
9B35	9B3C	Recommended
9B3D		Uncommon_Use
9B3E	9B3F	Recommended
9B40		Uncommon_Use
9B41	9B4F	Recommended
9B50		Uncommon_Use
9B51	9B56	Recommended
9B57		Uncommon_Use
9B58	9B61	Recommended
9B62		Uncommon_Use
9B63	9B71	Recommended
9B72		Uncommon_Use
9B73	9B88	Recommended
9B89		Uncommon_Use
9B8A	9B8B	Recommended
9B8C		Uncommon_Use
9B8D	9B98	Recommended
9B99		Uncommon_Use
9B9A	9BC1	Recommended
9BC2		Uncommon_Use
9BC3	9BF5	Recommended
9BF6		Uncommon_Use
9BF7	9BFF	Recommended
9C00	9C01	Uncommon_Use
9C02		Recommended
9C03		Uncommon_Use
9C04	9C41	Recommended
9C42		Uncommon_Use
9C43	9C4E	Recommended
9C4F		Uncommon_Use
9C50		Recommended
9C51		Uncommon_Use
9C52	9C60	Recommended
9C61		Uncommon_Use
9C62	9C63	Recommended
9C64		Uncommon_Use
9C65	9C7A	Recommended
9C7B		Uncommon_Use
9C7C	9D0B	Recommended
9D0C	9D0D	Uncommon_Use
9D0E	9D10	Recommended
9D11		Uncommon_Use
9D12	9D26	Recommended
9D27		Uncommon_Use
9D28	9D34	Recommended
9D35		Uncommon_Use
9D36	9D3B	Recommended
9D3C		Uncommon_Use
9D3D	9D6C	Recommended
9D6D		Uncommon_Use
9D6E	9D94	Recommended
9D95		Uncommon_Use
9D96	9DAD	Recommended
9DAE		Uncommon_Use
9DAF	9DBC	Recommended
9DBD		Uncommon_Use
9DBE	9DBF	Recommended
9DC0		Uncommon_Use
9DC1	9DE9	Recommended
9DEA		Uncommon_Use
9DEB	9DFB	Recommended
9DFC		Uncommon_Use
9DFD	9E0D	Recommended
9E0E		Uncommon_Use
9E0F	9E15	Recommended
9E16		Uncommon_Use
9E17	9E1B	Recommended
9E1C		Uncommon_Use
9E1D	9E7A	Recommended
9E7B		Uncommon_Use
9E7C	9E8E	Recommended
9E8F	9E90	Uncommon_Use
9E91	9E97	Recommended
9E98		Uncommon_Use
9E99	9E9D	Recommended
9E9E		Uncommon_Use
9E9F	9EA1	Recommended
9EA2		Uncommon_Use
9EA3	9EAA	Recommended
9EAB	9EAC	Uncommon_Use
9EAD	9EB0	Recommended
9EB1		Uncommon_Use
9EB2	9EEB	Recommended
9EEC		Uncommon_Use
9EED	9EF0	Recommended
9EF1		Uncommon_Use
9EF2	9F02	Recommended
9F03		Uncommon_Use
9F04	9F10	Recommended
9F11		Uncommon_Use
9F12	9F13	Recommended
9F14		Uncommon_Use
9F15	9F25	Recommended
9F26		Uncommon_Use
9F27	9F44	Recommended
9F45		Uncommon_Use
9F46	9F52	Recommended
9F53		Uncommon_Use
9F54	9F6C	Recommended
9F6D		Uncommon_Use
9F6E	9FA0	Recommended
9FA1		Uncommon_Use
9FA2		Recommended
9FA3		Uncommon_Use
9FA4	9FA5	Recommended
9FA6	9FFF	Uncommon_Use
A000	A48C	Limited_Use
A490	A4C6	Limited_Use Not_XID
A4D0	A4FD	Limited_Use
A4FE	A4FF	Limited_Use Not_XID
A500	A60C	Limited_Use
A60D	A60F	Limited_Use Not_XID
A610	A612	Limited_Use Obsolete
A613	A629	Limited_Use
A62A	A62B	Limited_Use Obsolete
A640	A66E	Obsolete
A66F		Uncommon_Use
A670	A673	Obsolete Not_XID
A674	A67B	Obsolete
A67C	A67D	Uncommon_Use
A67E		Not_XID
A67F	A69B	Obsolete
A69C	A69D	Not_NFKC
A69E		Uncommon_Use Obsolete
A69F		Obsolete
A6A0	A6F1	Limited_Use
A6F2	A6F7	Limited_Use Not_XID
A700	A707	Obsolete Not_XID
A708	A716	Technical Not_XID
A717	A71F	Technical
A720	A721	Not_XID
A722	A72F	Technical Obsolete
A730	A76F	Obsolete
A770		Not_NFKC
A771	A787	Obsolete
A788		Technical
A789	A78A	Not_XID
A78B	A78C	Uncommon_Use
A78D		Recommended
A78E		Technical
A78F		Uncommon_Use
A790	A791	Obsolete
A792	A793	Uncommon_Use
A794	A7A9	Obsolete
A7AA		Recommended
A7AB	A7AD	Obsolete
A7AE	A7AF	Technical
A7B0	A7B1	Obsolete
A7B2	A7B9	Uncommon_Use
A7BA	A7BF	Technical
A7C0	A7C1	Obsolete
A7C2	A7C3	Uncommon_Use
A7C4		Obsolete
A7C5	A7C6	Technical
A7C7	A7CA	Obsolete
A7CB	A7CF	Uncommon_Use
A7D0	A7D9	Obsolete
A7DA	A7DC	Uncommon_Use
A7F1	A7F4	Not_NFKC
A7F5	A7F7	Obsolete
A7F8	A7F9	Not_NFKC
A7FA		Technical
A7FB	A7FF	Obsolete
A800	A827	Limited_Use
A828	A82B	Limited_Use Not_XID
A82C		Limited_Use
A830	A839	Not_XID
A840	A873	Exclusion
A874	A877	Exclusion Not_XID
A880	A8C5	Limited_Use
A8CE	A8CF	Limited_Use Not_XID
A8D0	A8D9	Limited_Use
A8E0	A8F7	Obsolete
A8F8	A8FA	Obsolete Not_XID
A8FB		Obsolete
A8FC		Uncommon_Use Obsolete Not_XID
A8FD		Uncommon_Use Obsolete
A8FE	A8FF	Obsolete
A900	A92D	Limited_Use
A92E		Not_XID
A92F		Limited_Use Not_XID
A930	A953	Exclusion
A95F		Exclusion Not_XID
A960	A97C	Obsolete
A980	A9C0	Limited_Use
A9C1	A9CD	Limited_Use Not_XID
A9CF		Limited_Use Uncommon_Use
A9D0	A9D9	Limited_Use
A9DE	A9DF	Limited_Use Not_XID
A9E0	A9E6	Obsolete
A9E7	A9FE	Uncommon_Use
AA00	AA36	Limited_Use
AA40	AA4D	Limited_Use
AA50	AA59	Limited_Use
AA5C	AA5F	Limited_Use Not_XID
AA60	AA76	Uncommon_Use
AA77	AA79	Not_XID
AA7A		Uncommon_Use
AA7B		Recommended
AA7C	AA7F	Uncommon_Use
AA80	AAC2	Limited_Use
AADB	AADD	Limited_Use
AADE	AADF	Limited_Use Not_XID
AAE0	AAEF	Limited_Use
AAF0	AAF1	Limited_Use Not_XID
AAF2	AAF6	Limited_Use
AB01	AB06	Uncommon_Use
AB09	AB0E	Uncommon_Use
AB11	AB16	Uncommon_Use
AB20	AB26	Uncommon_Use
AB28	AB2E	Uncommon_Use
AB30	AB5A	Obsolete
AB5B		Not_XID
AB5C	AB5F	Not_NFKC
AB60	AB63	Uncommon_Use
AB64	AB65	Obsolete
AB66	AB67	Uncommon_Use
AB68		Technical
AB69		Not_NFKC
AB6A	AB6B	Not_XID
AB70	ABEA	Limited_Use
ABEB		Limited_Use Not_XID
ABEC	ABED	Limited_Use
ABF0	ABF9	Limited_Use
AC00	D7A3	Recommended
D7B0	D7C6	Obsolete
D7CB	D7FB	Obsolete
F900	FA0D	Not_NFKC
FA0E	FA0F	Uncommon_Use
FA10		Not_NFKC
FA11		Uncommon_Use
FA12		Not_NFKC
FA13	FA14	Uncommon_Use
FA15	FA1E	Not_NFKC
FA1F		Uncommon_Use
FA20		Not_NFKC
FA21		Uncommon_Use
FA22		Not_NFKC
FA23	FA24	Uncommon_Use
FA25	FA26	Not_NFKC
FA27	FA29	Uncommon_Use
FA2A	FA6D	Not_NFKC
FA70	FAD9	Not_NFKC
FB00	FB06	Not_NFKC
FB13	FB17	Not_NFKC
FB1D		Not_NFKC
FB1E		Uncommon_Use Technical
FB1F	FB36	Not_NFKC
FB38	FB3C	Not_NFKC
FB3E		Not_NFKC
FB40	FB41	Not_NFKC
FB43	FB44	Not_NFKC
FB46	FBB1	Not_NFKC
FBB2	FBD2	Technical Not_XID
FBD3	FD3D	Not_NFKC
FD3E	FD4F	Technical Not_XID
FD50	FD8F	Not_NFKC
FD90	FD91	Technical Not_XID
FD92	FDC7	Not_NFKC
FDC8	FDCF	Technical Not_XID
FDF0	FDFC	Not_NFKC
FDFD	FDFF	Technical Not_XID
FE00	FE0F	Default_Ignorable
FE10	FE19	Not_NFKC
FE20	FE2D	Technical
FE2E	FE2F	Uncommon_Use Technical
FE30	FE44	Not_NFKC
FE45	FE46	Technical Not_XID
FE47	FE52	Not_NFKC
FE54	FE66	Not_NFKC
FE68	FE6B	Not_NFKC
FE70	FE72	Not_NFKC
FE73		Technical
FE74		Not_NFKC
FE76	FEFC	Not_NFKC
FEFF		Default_Ignorable
FF01	FF9F	Not_NFKC
FFA0		Default_Ignorable
FFA1	FFBE	Not_NFKC
FFC2	FFC7	Not_NFKC
FFCA	FFCF	Not_NFKC
FFD2	FFD7	Not_NFKC
FFDA	FFDC	Not_NFKC
FFE0	FFE6	Not_NFKC
FFE8	FFEE	Not_NFKC
FFF9	FFFD	Not_XID
10000	1000B	Exclusion
1000D	10026	Exclusion
10028	1003A	Exclusion
1003C	1003D	Exclusion
1003F	1004D	Exclusion
10050	1005D	Exclusion
10080	100FA	Exclusion
10100	10102	Exclusion Not_XID
10107	10133	Exclusion Not_XID
10137	1013F	Exclusion Not_XID
10140	10174	Obsolete
10175	1018E	Not_XID
10190	1019C	Not_XID
101A0		Not_XID
101D0	101FC	Obsolete Not_XID
101FD		Obsolete
10280	1029C	Exclusion
102A0	102D0	Exclusion
102E0		Obsolete
102E1	102FB	Obsolete Not_XID
10300	1031F	Exclusion
10320	10323	Exclusion Not_XID
1032D	1034A	Exclusion
10350	1037A	Exclusion
10380	1039D	Exclusion
1039F		Exclusion Not_XID
103A0	103C3	Exclusion
103C8	103CF	Exclusion
103D0		Exclusion Not_XID
103D1	103D5	Exclusion
10400	1049D	Exclusion
104A0	104A9	Exclusion
104B0	104D3	Limited_Use
104D8	104FB	Limited_Use
10500	10527	Exclusion
10530	10563	Exclusion
1056F		Exclusion Not_XID
10570	1057A	Exclusion
1057C	1058A	Exclusion
1058C	10592	Exclusion
10594	10595	Exclusion
10597	105A1	Exclusion
105A3	105B1	Exclusion
105B3	105B9	Exclusion
105BB	105BC	Exclusion
105C0	105F3	Exclusion
10600	10736	Exclusion
10740	10755	Exclusion
10760	10767	Exclusion
10780		Uncommon_Use
10781	10785	Not_NFKC
10787	107B0	Not_NFKC
107B2	107BA	Not_NFKC
10800	10805	Exclusion
10808		Exclusion
1080A	10835	Exclusion
10837	10838	Exclusion
1083C		Exclusion
1083F	10855	Exclusion
10857	1085F	Exclusion Not_XID
10860	10876	Exclusion
10877	1087F	Exclusion Not_XID
10880	1089E	Exclusion
108A7	108AF	Exclusion Not_XID
108E0	108F2	Exclusion
108F4	108F5	Exclusion
108FB	108FF	Exclusion Not_XID
10900	10915	Exclusion
10916	1091B	Exclusion Not_XID
1091F		Exclusion Not_XID
10920	10939	Exclusion
1093F		Exclusion Not_XID
10940	10959	Exclusion
10980	109B7	Exclusion
109BC	109BD	Exclusion Not_XID
109BE	109BF	Exclusion
109C0	109CF	Exclusion Not_XID
109D2	109FF	Exclusion Not_XID
10A00	10A03	Exclusion
10A05	10A06	Exclusion
10A0C	10A13	Exclusion
10A15	10A17	Exclusion
10A19	10A35	Exclusion
10A38	10A3A	Exclusion
10A3F		Exclusion
10A40	10A48	Exclusion Not_XID
10A50	10A58	Exclusion Not_XID
10A60	10A7C	Exclusion
10A7D	10A7F	Exclusion Not_XID
10A80	10A9C	Exclusion
10A9D	10A9F	Exclusion Not_XID
10AC0	10AC7	Exclusion
10AC8		Exclusion Not_XID
10AC9	10AE6	Exclusion
10AEB	10AF6	Exclusion Not_XID
10B00	10B35	Exclusion
10B39	10B3F	Exclusion Not_XID
10B40	10B55	Exclusion
10B58	10B5F	Exclusion Not_XID
10B60	10B72	Exclusion
10B78	10B7F	Exclusion Not_XID
10B80	10B91	Exclusion
10B99	10B9C	Exclusion Not_XID
10BA9	10BAF	Exclusion Not_XID
10C00	10C48	Exclusion
10C80	10CB2	Exclusion
10CC0	10CF2	Exclusion
10CFA	10CFF	Exclusion Not_XID
10D00	10D27	Limited_Use
10D30	10D39	Limited_Use
10D40	10D65	Exclusion
10D69	10D6D	Exclusion
10D6E		Exclusion Not_XID
10D6F	10D85	Exclusion
10D8E	10D8F	Exclusion Not_XID
10E60	10E7E	Not_XID
10E80	10EA9	Exclusion
10EAB	10EAC	Exclusion
10EAD		Exclusion Not_XID
10EB0	10EB1	Exclusion
10EC2	10EC4	Uncommon_Use
10EC5	10EC6	Technical
10EC7		Uncommon_Use
10ED0	10ED8	Not_XID
10EFA		Uncommon_Use
10EFB		Technical
10EFC	10EFF	Uncommon_Use
10F00	10F1C	Exclusion
10F1D	10F26	Exclusion Not_XID
10F27		Exclusion
10F30	10F50	Exclusion
10F51	10F59	Exclusion Not_XID
10F70	10F85	Exclusion
10F86	10F89	Exclusion Not_XID
10FB0	10FC4	Exclusion
10FC5	10FCB	Exclusion Not_XID
10FE0	10FF6	Exclusion
11000	11046	Exclusion
11047	1104D	Exclusion Not_XID
11052	11065	Exclusion Not_XID
11066	11075	Exclusion
1107F	110BA	Exclusion
110BB	110C1	Exclusion Not_XID
110C2		Exclusion
110CD		Exclusion Not_XID
110D0	110E8	Exclusion
110F0	110F9	Exclusion
11100	11134	Limited_Use
11136	1113F	Limited_Use
11140	11143	Limited_Use Not_XID
11144	11147	Limited_Use
11150	11173	Exclusion
11174	11175	Exclusion Not_XID
11176		Exclusion
11180	111C4	Exclusion
111C5	111C8	Exclusion Not_XID
111C9	111CC	Exclusion
111CD		Exclusion Not_XID
111CE	111DA	Exclusion
111DB		Exclusion Not_XID
111DC		Exclusion
111DD	111DF	Exclusion Not_XID
111E1	111F4	Not_XID
11200	11211	Exclusion
11213	11237	Exclusion
11238	1123D	Exclusion Not_XID
1123E	11241	Exclusion
11280	11286	Exclusion
11288		Exclusion
1128A	1128D	Exclusion
1128F	1129D	Exclusion
1129F	112A8	Exclusion
112A9		Exclusion Not_XID
112B0	112EA	Exclusion
112F0	112F9	Exclusion
11300		Exclusion
11301		Recommended
11302		Exclusion
11303		Recommended
11305	1130C	Exclusion
1130F	11310	Exclusion
11313	11328	Exclusion
1132A	11330	Exclusion
11332	11333	Exclusion
11335	11339	Exclusion
1133B		Uncommon_Use
1133C		Recommended
1133D	11344	Exclusion
11347	11348	Exclusion
1134B	1134D	Exclusion
11350		Exclusion
11357		Exclusion
1135D	11363	Exclusion
11366	1136C	Exclusion
11370	11374	Exclusion
11380	11389	Exclusion
1138B		Exclusion
1138E		Exclusion
11390	113B5	Exclusion
113B7	113C0	Exclusion
113C2		Exclusion
113C5		Exclusion
113C7	113CA	Exclusion
113CC	113D3	Exclusion
113D4	113D5	Exclusion Not_XID
113D7	113D8	Exclusion Not_XID
113E1	113E2	Exclusion
11400	1144A	Limited_Use
1144B	1144F	Limited_Use Not_XID
11450	11459	Limited_Use
1145A	1145B	Limited_Use Not_XID
1145D		Limited_Use Not_XID
1145E	11461	Limited_Use
11480	114C5	Exclusion
114C6		Exclusion Not_XID
114C7		Exclusion
114D0	114D9	Exclusion
11580	115B5	Exclusion
115B8	115C0	Exclusion
115C1	115D7	Exclusion Not_XID
115D8	115DD	Exclusion
11600	11640	Exclusion
11641	11643	Exclusion Not_XID
11644		Exclusion
11650	11659	Exclusion
11660	1166C	Exclusion Not_XID
11680	116B8	Exclusion
116B9		Exclusion Not_XID
116C0	116C9	Exclusion
116D0	116E3	Uncommon_Use
11700	1171A	Exclusion
1171D	1172B	Exclusion
11730	11739	Exclusion
1173A	1173F	Exclusion Not_XID
11740	11746	Exclusion
11800	1183A	Exclusion
1183B		Exclusion Not_XID
118A0	118E9	Exclusion
118EA	118F2	Exclusion Not_XID
118FF	11906	Exclusion
11909		Exclusion
1190C	11913	Exclusion
11915	11916	Exclusion
11918	11935	Exclusion
11937	11938	Exclusion
1193B	11943	Exclusion
11944	11946	Exclusion Not_XID
11950	11959	Exclusion
119A0	119A7	Exclusion
119AA	119D7	Exclusion
119DA	119E1	Exclusion
119E2		Exclusion Not_XID
119E3	119E4	Exclusion
11A00	11A3E	Exclusion
11A3F	11A46	Exclusion Not_XID
11A47		Exclusion
11A50	11A99	Exclusion
11A9A	11A9C	Exclusion Not_XID
11A9D		Exclusion
11A9E	11AA2	Exclusion Not_XID
11AB0	11ABF	Limited_Use
11AC0	11AF8	Exclusion
11B00	11B09	Not_XID
11B60	11B67	Exclusion
11BC0	11BE0	Exclusion
11BE1		Exclusion Not_XID
11BF0	11BF9	Exclusion
11C00	11C08	Exclusion
11C0A	11C36	Exclusion
11C38	11C40	Exclusion
11C41	11C45	Exclusion Not_XID
11C50	11C59	Exclusion
11C5A	11C6C	Exclusion Not_XID
11C70	11C71	Exclusion Not_XID
11C72	11C8F	Exclusion
11C92	11CA7	Exclusion
11CA9	11CB6	Exclusion
11D00	11D06	Exclusion
11D08	11D09	Exclusion
11D0B	11D36	Exclusion
11D3A		Exclusion
11D3C	11D3D	Exclusion
11D3F	11D47	Exclusion
11D50	11D59	Exclusion
11D60	11D65	Exclusion
11D67	11D68	Exclusion
11D6A	11D8E	Exclusion
11D90	11D91	Exclusion
11D93	11D98	Exclusion
11DA0	11DA9	Exclusion
11DB0	11DDB	Exclusion
11DE0	11DE9	Exclusion
11EE0	11EF6	Exclusion
11EF7	11EF8	Exclusion Not_XID
11F00	11F10	Exclusion
11F12	11F3A	Exclusion
11F3E	11F42	Exclusion
11F43	11F4F	Exclusion Not_XID
11F50	11F5A	Exclusion
11FB0		Limited_Use
11FC0	11FF1	Not_XID
11FFF		Not_XID
12000	12399	Exclusion
12400	1246E	Exclusion
12470	12474	Exclusion Not_XID
12480	12543	Exclusion
12F90	12FF0	Exclusion
12FF1	12FF2	Exclusion Not_XID
13000	1342F	Exclusion
13430	1343F	Exclusion Not_XID
13440	13455	Exclusion
13460	143FA	Exclusion
14400	14646	Exclusion
16100	16139	Exclusion
16800	16A38	Limited_Use
16A40	16A5E	Uncommon_Use Exclusion
16A60	16A69	Uncommon_Use Exclusion
16A6E	16A6F	Exclusion Not_XID
16A70	16ABE	Exclusion
16AC0	16AC9	Exclusion
16AD0	16AED	Exclusion
16AF0	16AF4	Exclusion
16AF5		Exclusion Not_XID
16B00	16B36	Exclusion
16B37	16B3F	Exclusion Not_XID
16B40	16B43	Exclusion
16B44	16B45	Exclusion Not_XID
16B50	16B59	Exclusion
16B5B	16B61	Exclusion Not_XID
16B63	16B77	Exclusion
16B7D	16B8F	Exclusion
16D40	16D6C	Exclusion
16D6D	16D6F	Exclusion Not_XID
16D70	16D79	Exclusion
16E40	16E7F	Exclusion
16E80	16E9A	Exclusion Not_XID
16EA0	16EB8	Exclusion
16EBB	16ED3	Exclusion
16F00	16F4A	Limited_Use
16F4F	16F87	Limited_Use
16F8F	16F9F	Limited_Use
16FE0	16FE1	Exclusion
16FE2		Not_XID
16FE3		Obsolete
16FE4		Exclusion
16FF0	16FF1	Obsolete
16FF2	16FF6	Technical
17000	18CD5	Exclusion
18CFF	18D1E	Exclusion
18D80	18DF2	Exclusion
1AFF0	1AFF3	Uncommon_Use
1AFF5	1AFFB	Uncommon_Use
1AFFD	1AFFE	Uncommon_Use
1B000	1B122	Obsolete
1B132		Obsolete
1B150	1B152	Obsolete
1B155		Obsolete
1B164	1B167	Obsolete
1B170	1B2FB	Exclusion
1BC00	1BC6A	Exclusion
1BC70	1BC7C	Exclusion
1BC80	1BC88	Exclusion
1BC90	1BC99	Exclusion
1BC9C		Exclusion Not_XID
1BC9D	1BC9E	Exclusion
1BC9F		Exclusion Not_XID
1BCA0	1BCA3	Default_Ignorable
1CC00	1CCD5	Not_XID
1CCD6	1CCF9	Not_NFKC
1CCFA	1CCFC	Not_XID
1CD00	1CEB3	Not_XID
1CEBA	1CED0	Not_XID
1CEE0	1CEF0	Not_XID
1CF00	1CF2D	Technical
1CF30	1CF46	Technical
1CF50	1CFC3	Technical Not_XID
1D000	1D0F5	Technical Not_XID
1D100	1D126	Technical Not_XID
1D129	1D15D	Technical Not_XID
1D15E	1D164	Not_NFKC
1D165	1D169	Technical
1D16A	1D16C	Technical Not_XID
1D16D	1D172	Technical
1D173	1D17A	Default_Ignorable
1D17B	1D182	Technical
1D183	1D184	Technical Not_XID
1D185	1D18B	Technical
1D18C	1D1A9	Technical Not_XID
1D1AA	1D1AD	Technical
1D1AE	1D1BA	Technical Not_XID
1D1BB	1D1C0	Not_NFKC
1D1C1	1D1DD	Technical Not_XID
1D1DE	1D1E8	Uncommon_Use Technical Not_XID
1D1E9	1D1EA	Technical Not_XID
1D200	1D241	Obsolete Not_XID
1D242	1D244	Technical Obsolete
1D245		Obsolete Not_XID
1D2C0	1D2D3	Not_XID
1D2E0	1D2F3	Not_XID
1D300	1D356	Technical Not_XID
1D360	1D378	Not_XID
1D400	1D454	Not_NFKC
1D456	1D49C	Not_NFKC
1D49E	1D49F	Not_NFKC
1D4A2		Not_NFKC
1D4A5	1D4A6	Not_NFKC
1D4A9	1D4AC	Not_NFKC
1D4AE	1D4B9	Not_NFKC
1D4BB		Not_NFKC
1D4BD	1D4C3	Not_NFKC
1D4C5	1D505	Not_NFKC
1D507	1D50A	Not_NFKC
1D50D	1D514	Not_NFKC
1D516	1D51C	Not_NFKC
1D51E	1D539	Not_NFKC
1D53B	1D53E	Not_NFKC
1D540	1D544	Not_NFKC
1D546		Not_NFKC
1D54A	1D550	Not_NFKC
1D552	1D6A5	Not_NFKC
1D6A8	1D7CB	Not_NFKC
1D7CE	1D7FF	Not_NFKC
1D800	1D9FF	Exclusion Not_XID
1DA00	1DA36	Exclusion
1DA37	1DA3A	Exclusion Not_XID
1DA3B	1DA6C	Exclusion
1DA6D	1DA74	Exclusion Not_XID
1DA75		Exclusion
1DA76	1DA83	Exclusion Not_XID
1DA84		Exclusion
1DA85	1DA8B	Exclusion Not_XID
1DA9B	1DA9F	Exclusion
1DAA1	1DAAF	Exclusion
1DF00	1DF1E	Technical
1DF25	1DF2A	Technical
1E000	1E006	Exclusion
1E008	1E018	Exclusion
1E01B	1E021	Exclusion
1E023	1E024	Exclusion
1E026	1E02A	Exclusion
1E030	1E06D	Not_NFKC
1E08F		Obsolete
1E100	1E12C	Limited_Use
1E130	1E13D	Limited_Use
1E140	1E149	Limited_Use
1E14E		Limited_Use
1E14F		Limited_Use Not_XID
1E290	1E2AE	Exclusion
1E2C0	1E2F9	Limited_Use
1E2FF		Limited_Use Not_XID
1E4D0	1E4F9	Exclusion
1E5D0	1E5FA	Exclusion
1E5FF		Exclusion Not_XID
1E6C0	1E6DE	Exclusion
1E6E0	1E6F5	Exclusion
1E6FE	1E6FF	Exclusion
1E7E0	1E7E6	Recommended
1E7E8	1E7EB	Recommended
1E7ED	1E7EE	Recommended
1E7F0	1E7FE	Recommended
1E800	1E8C4	Exclusion
1E8C7	1E8CF	Exclusion Not_XID
1E8D0	1E8D6	Exclusion
1E900	1E94B	Limited_Use
1E950	1E959	Limited_Use
1E95E	1E95F	Limited_Use Not_XID
1EC71	1ECB4	Not_XID
1ED01	1ED3D	Not_XID
1EE00	1EE03	Not_NFKC
1EE05	1EE1F	Not_NFKC
1EE21	1EE22	Not_NFKC
1EE24		Not_NFKC
1EE27		Not_NFKC
1EE29	1EE32	Not_NFKC
1EE34	1EE37	Not_NFKC
1EE39		Not_NFKC
1EE3B		Not_NFKC
1EE42		Not_NFKC
1EE47		Not_NFKC
1EE49		Not_NFKC
1EE4B		Not_NFKC
1EE4D	1EE4F	Not_NFKC
1EE51	1EE52	Not_NFKC
1EE54		Not_NFKC
1EE57		Not_NFKC
1EE59		Not_NFKC
1EE5B		Not_NFKC
1EE5D		Not_NFKC
1EE5F		Not_NFKC
1EE61	1EE62	Not_NFKC
1EE64		Not_NFKC
1EE67	1EE6A	Not_NFKC
1EE6C	1EE72	Not_NFKC
1EE74	1EE77	Not_NFKC
1EE79	1EE7C	Not_NFKC
1EE7E		Not_NFKC
1EE80	1EE89	Not_NFKC
1EE8B	1EE9B	Not_NFKC
1EEA1	1EEA3	Not_NFKC
1EEA5	1EEA9	Not_NFKC
1EEAB	1EEBB	Not_NFKC
1EEF0	1EEF1	Not_XID
1F000	1F02B	Not_XID
1F030	1F093	Not_XID
1F0A0	1F0AE	Not_XID
1F0B1	1F0BF	Not_XID
1F0C1	1F0CF	Not_XID
1F0D1	1F0F5	Not_XID
1F100	1F10A	Not_NFKC
1F10B	1F10F	Not_XID
1F110	1F12E	Not_NFKC
1F12F		Not_XID
1F130	1F14F	Not_NFKC
1F150	1F169	Not_XID
1F16A	1F16C	Not_NFKC
1F16D	1F18F	Not_XID
1F190		Not_NFKC
1F191	1F1AD	Not_XID
1F1E6	1F1FF	Not_XID
1F200	1F202	Not_NFKC
1F210	1F23B	Not_NFKC
1F240	1F248	Not_NFKC
1F250	1F251	Not_NFKC
1F260	1F265	Not_XID
1F300	1F54E	Not_XID
1F54F		Uncommon_Use Not_XID
1F550	1F6D8	Not_XID
1F6DC	1F6EC	Not_XID
1F6F0	1F6FC	Not_XID
1F700	1F7D9	Not_XID
1F7E0	1F7EB	Not_XID
1F7F0		Not_XID
1F800	1F80B	Not_XID
1F810	1F847	Not_XID
1F850	1F859	Not_XID
1F860	1F887	Not_XID
1F890	1F8AD	Not_XID
1F8B0	1F8BB	Not_XID
1F8C0	1F8C1	Not_XID
1F8D0	1F8D8	Not_XID
1F900	1FA57	Not_XID
1FA60	1FA6D	Not_XID
1FA70	1FA7C	Not_XID
1FA80	1FA8A	Not_XID
1FA8E	1FAC6	Not_XID
1FAC8		Not_XID
1FACD	1FADC	Not_XID
1FADF	1FAEA	Not_XID
1FAEF	1FAF8	Not_XID
1FB00	1FB92	Not_XID
1FB94	1FBEF	Not_XID
1FBF0	1FBF9	Not_NFKC
1FBFA		Not_XID
20000	2070D	Uncommon_Use
2070E		Recommended
2070F	20730	Uncommon_Use
20731		Recommended
20732	20778	Uncommon_Use
20779		Recommended
2077A	20C52	Uncommon_Use
20C53		Recommended
20C54	20C77	Uncommon_Use
20C78		Recommended
20C79	20C95	Uncommon_Use
20C96		Recommended
20C97	20CCE	Uncommon_Use
20CCF		Recommended
20CD0	20CD4	Uncommon_Use
20CD5		Recommended
20CD6	20D14	Uncommon_Use
20D15		Recommended
20D16	20D7B	Uncommon_Use
20D7C		Recommended
20D7D	20D7E	Uncommon_Use
20D7F		Recommended
20D80	20E0D	Uncommon_Use
20E0E	20E0F	Recommended
20E10	20E76	Uncommon_Use
20E77		Recommended
20E78	20E9C	Uncommon_Use
20E9D		Recommended
20E9E	20EA1	Uncommon_Use
20EA2		Recommended
20EA3	20ED6	Uncommon_Use
20ED7		Recommended
20ED8	20EF8	Uncommon_Use
20EF9	20EFA	Recommended
20EFB	20F2C	Uncommon_Use
20F2D	20F2E	Recommended
20F2F	20F4B	Uncommon_Use
20F4C		Recommended
20F4D	20FB3	Uncommon_Use
20FB4		Recommended
20FB5	20FBB	Uncommon_Use
20FBC		Recommended
20FBD	20FE9	Uncommon_Use
20FEA		Recommended
20FEB	2105B	Uncommon_Use
2105C		Recommended
2105D	2106E	Uncommon_Use
2106F		Recommended
21070	21074	Uncommon_Use
21075	21076	Recommended
21077	2107A	Uncommon_Use
2107B		Recommended
2107C	210C0	Uncommon_Use
210C1		Recommended
210C2	210C8	Uncommon_Use
210C9		Recommended
210CA	211D8	Uncommon_Use
211D9		Recommended
211DA	220C6	Uncommon_Use
220C7		Recommended
220C8	227B4	Uncommon_Use
227B5		Recommended
227B6	22AD4	Uncommon_Use
22AD5		Recommended
22AD6	22B42	Uncommon_Use
22B43		Recommended
22B44	22BC9	Uncommon_Use
22BCA		Recommended
22BCB	22C50	Uncommon_Use
22C51		Recommended
22C52	22C54	Uncommon_Use
22C55		Recommended
22C56	22CC1	Uncommon_Use
22CC2		Recommended
22CC3	22D07	Uncommon_Use
22D08		Recommended
22D09	22D4B	Uncommon_Use
22D4C		Recommended
22D4D	22D66	Uncommon_Use
22D67		Recommended
22D68	22EB2	Uncommon_Use
22EB3		Recommended
22EB4	23CB6	Uncommon_Use
23CB7		Recommended
23CB8	244D2	Uncommon_Use
244D3		Recommended
244D4	24DB7	Uncommon_Use
24DB8		Recommended
24DB9	24DE9	Uncommon_Use
24DEA		Recommended
24DEB	2512A	Uncommon_Use
2512B		Recommended
2512C	26257	Uncommon_Use
26258		Recommended
26259	267CB	Uncommon_Use
267CC		Recommended
267CD	269F1	Uncommon_Use
269F2		Recommended
269F3	269F9	Uncommon_Use
269FA		Recommended
269FB	27A3D	Uncommon_Use
27A3E		Recommended
27A3F	2815C	Uncommon_Use
2815D		Recommended
2815E	28206	Uncommon_Use
28207		Recommended
28208	282E1	Uncommon_Use
282E2		Recommended
282E3	28CC9	Uncommon_Use
28CCA		Recommended
28CCB	28CCC	Uncommon_Use
28CCD		Recommended
28CCE	28CD1	Uncommon_Use
28CD2		Recommended
28CD3	29D97	Uncommon_Use
29D98		Recommended
29D99	2A6DF	Uncommon_Use
2A700	2B81D	Uncommon_Use
2B820	2CEAD	Uncommon_Use
2CEB0	2EBE0	Uncommon_Use
2EBF0	2EE5D	Uncommon_Use
2F800	2FA1D	Not_NFKC
30000	3134A	Uncommon_Use
31350	33479	Uncommon_Use
E0001		Deprecated
E0020	E007F	Default_Ignorable
E0100	E01EF	Default_Ignorable
END
