# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 17.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.



# The name this table is to be known by, with the format of the mappings in
# the main body of the table, and what all code points missing from this file
# map to.
$Unicode::UCD::SwashInfo{'ToIdentifierStatus'}{'format'} = 's'; # string
$Unicode::UCD::SwashInfo{'ToIdentifierStatus'}{'missing'} = 'Restricted';

return <<'END';
27		Allowed
2D	2E	Allowed
30	3A	Allowed
41	5A	Allowed
5F		Allowed
61	7A	Allowed
B7		Allowed
C0	D6	Allowed
D8	F6	Allowed
F8	113	Allowed
116	12B	Allowed
12E	131	Allowed
134	137	Allowed
139	13E	Allowed
141	148	Allowed
14A	14D	Allowed
150	155	Allowed
158	161	Allowed
164	17E	Allowed
181		Allowed
186		Allowed
189	18A	Allowed
18E	192	Allowed
194		Allowed
196	199	Allowed
19D		Allowed
1A0	1A1	Allowed
1AF	1B0	Allowed
1B2	1B4	Allowed
1B7		Allowed
1CD	1D4	Allowed
1DD		Allowed
1E6	1E9	Allowed
1EE	1EF	Allowed
1F8	1F9	Allowed
218	21B	Allowed
244		Allowed
24C	24D	Allowed
253	254	Allowed
256	257	Allowed
259		Allowed
25B		Allowed
263		Allowed
268	269	Allowed
272		Allowed
289		Allowed
28B		Allowed
292		Allowed
2BB	2BC	Allowed
300	304	Allowed
306	30C	Allowed
31B		Allowed
323		Allowed
326	328	Allowed
331		Allowed
386		Allowed
388	38A	Allowed
38C		Allowed
38E	3A1	Allowed
3A3	3CE	Allowed
401	40C	Allowed
40E	44F	Allowed
451	45C	Allowed
45E	45F	Allowed
490	49B	Allowed
49E	4A5	Allowed
4A8	4B7	Allowed
4BA	4C0	Allowed
4CF	4D9	Allowed
4DC	4E9	Allowed
4EE	4F5	Allowed
4F8	4F9	Allowed
524	525	Allowed
531	556	Allowed
561	586	Allowed
58A		Allowed
5D0	5EA	Allowed
5F3	5F4	Allowed
620	63A	Allowed
63D		Allowed
641	652	Allowed
654	655	Allowed
660	669	Allowed
670		Allowed
672		Allowed
674		Allowed
679	68F	Allowed
691	69A	Allowed
69F	6A0	Allowed
6A2		Allowed
6A4	6AB	Allowed
6AD	6B1	Allowed
6B3		Allowed
6B5	6B7	Allowed
6BA	6BE	Allowed
6C0	6D3	Allowed
6D5		Allowed
6EE	6F9	Allowed
6FD	6FF	Allowed
751	752	Allowed
756		Allowed
760		Allowed
762	763	Allowed
766	768	Allowed
76A		Allowed
76E	771	Allowed
780	7B1	Allowed
88F		Allowed
8A0		Allowed
8A2	8A9	Allowed
8BB	8C2	Allowed
8C7		Allowed
901	903	Allowed
905	90B	Allowed
90D	928	Allowed
92A	933	Allowed
935	93C	Allowed
93E	943	Allowed
945	94D	Allowed
94F		Allowed
956	957	Allowed
966	96F	Allowed
972	977	Allowed
97B	97C	Allowed
97E	97F	Allowed
981	983	Allowed
985	98B	Allowed
98F	990	Allowed
993	9A8	Allowed
9AA	9B0	Allowed
9B2		Allowed
9B6	9B9	Allowed
9BC		Allowed
9BE	9C4	Allowed
9C7	9C8	Allowed
9CB	9CE	Allowed
9E6	9F1	Allowed
A02		Allowed
A05	A0A	Allowed
A0F	A10	Allowed
A13	A28	Allowed
A2A	A30	Allowed
A32		Allowed
A35		Allowed
A38	A39	Allowed
A3C		Allowed
A3E	A42	Allowed
A47	A48	Allowed
A4B	A4D	Allowed
A5C		Allowed
A70	A71	Allowed
A82	A83	Allowed
A85	A8D	Allowed
A8F	A91	Allowed
A93	AA8	Allowed
AAA	AB0	Allowed
AB2	AB3	Allowed
AB5	AB9	Allowed
ABC		Allowed
ABE	AC5	Allowed
AC7	AC9	Allowed
ACB	ACD	Allowed
AE6	AEF	Allowed
B01	B03	Allowed
B05	B0B	Allowed
B0F	B10	Allowed
B13	B28	Allowed
B2A	B30	Allowed
B32	B33	Allowed
B36	B39	Allowed
B3C		Allowed
B3E	B43	Allowed
B47	B48	Allowed
B4B	B4D	Allowed
B56		Allowed
B5F		Allowed
B71		Allowed
B83		Allowed
B85	B8A	Allowed
B8E	B90	Allowed
B92	B95	Allowed
B99	B9A	Allowed
B9C		Allowed
B9E	B9F	Allowed
BA3	BA4	Allowed
BA8	BAA	Allowed
BAE	BB9	Allowed
BBE	BC2	Allowed
BC6	BC8	Allowed
BCA	BCD	Allowed
C02	C03	Allowed
C05	C0B	Allowed
C0E	C10	Allowed
C12	C28	Allowed
C2A	C30	Allowed
C32	C33	Allowed
C35	C39	Allowed
C3E	C44	Allowed
C46	C48	Allowed
C4A	C4D	Allowed
C82	C83	Allowed
C85	C8B	Allowed
C8E	C90	Allowed
C92	CA8	Allowed
CAA	CB0	Allowed
CB2	CB3	Allowed
CB5	CB9	Allowed
CBE	CC3	Allowed
CC6	CC8	Allowed
CCA	CCD	Allowed
CE6	CEF	Allowed
D02	D03	Allowed
D05	D0B	Allowed
D0E	D10	Allowed
D12	D28	Allowed
D2A	D39	Allowed
D3E	D43	Allowed
D46	D48	Allowed
D4A	D4B	Allowed
D4D		Allowed
D57		Allowed
D7A	D7F	Allowed
D82	D83	Allowed
D85	D8D	Allowed
D91	D96	Allowed
D9A	D9D	Allowed
D9F	DB1	Allowed
DB3	DBB	Allowed
DBD		Allowed
DC0	DC6	Allowed
DCA		Allowed
DCF	DD4	Allowed
DD6		Allowed
DD8	DDE	Allowed
DF2		Allowed
E01	E32	Allowed
E34	E3A	Allowed
E40	E4D	Allowed
E50	E59	Allowed
E81	E82	Allowed
E84		Allowed
E87	E88	Allowed
E8A		Allowed
E8D		Allowed
E94	E97	Allowed
E99	E9F	Allowed
EA1	EA3	Allowed
EA5		Allowed
EA7		Allowed
EAA	EAB	Allowed
EAD	EAE	Allowed
EB0	EB2	Allowed
EB4	EB9	Allowed
EBB	EBD	Allowed
EC0	EC4	Allowed
EC6		Allowed
EC8	ECD	Allowed
ED0	ED9	Allowed
F0B		Allowed
F20	F29	Allowed
F40	F42	Allowed
F44	F47	Allowed
F49	F4C	Allowed
F4E	F51	Allowed
F53	F56	Allowed
F58	F5B	Allowed
F5D	F68	Allowed
F71	F72	Allowed
F74		Allowed
F7A	F80	Allowed
F84		Allowed
F90	F92	Allowed
F94	F97	Allowed
F99	F9C	Allowed
F9E	FA1	Allowed
FA3	FA6	Allowed
FA8	FAB	Allowed
FAD		Allowed
FB1	FB8	Allowed
FBA	FBC	Allowed
1000	1049	Allowed
105A	1064	Allowed
1075	108A	Allowed
108F		Allowed
10C7		Allowed
10CD		Allowed
10D0	10F0	Allowed
1200	1206	Allowed
1208	1248	Allowed
124A	124D	Allowed
1250	1256	Allowed
1258		Allowed
125A	125D	Allowed
1260	1286	Allowed
1288		Allowed
128A	128D	Allowed
1290	12AE	Allowed
12B0		Allowed
12B2	12B5	Allowed
12B8	12BE	Allowed
12C0		Allowed
12C2	12C5	Allowed
12C8	12D6	Allowed
12D8	12F7	Allowed
1300	130E	Allowed
1310		Allowed
1312	1315	Allowed
1318	131E	Allowed
1320	1346	Allowed
1348	1359	Allowed
1780	179C	Allowed
179F	17A2	Allowed
17A5	17A7	Allowed
17AA	17B3	Allowed
17B6	17CD	Allowed
17D0		Allowed
17D2		Allowed
17E0	17E9	Allowed
1C90	1CBA	Allowed
1CBD	1CBF	Allowed
1E0C	1E0D	Allowed
1E12	1E13	Allowed
1E20	1E21	Allowed
1E24	1E25	Allowed
1E36	1E37	Allowed
1E3C	1E3F	Allowed
1E42	1E4B	Allowed
1E5A	1E5B	Allowed
1E62	1E63	Allowed
1E6C	1E6D	Allowed
1E70	1E71	Allowed
1E8C	1E8D	Allowed
1E92	1E93	Allowed
1E9E		Allowed
1EA0	1EF9	Allowed
1FA0	1FAF	Allowed
1FB2	1FB4	Allowed
1FEC		Allowed
2010		Allowed
2019		Allowed
2027		Allowed
3005	3007	Allowed
3041	3096	Allowed
309D	309E	Allowed
30A0	30FE	Allowed
3447		Allowed
3473		Allowed
34E4		Allowed
3577		Allowed
359E		Allowed
35A1		Allowed
35AD		Allowed
35BF		Allowed
35CE		Allowed
35F3		Allowed
35FE		Allowed
360E		Allowed
361A		Allowed
3918		Allowed
3960		Allowed
396E		Allowed
39CF	39D0	Allowed
39DB		Allowed
39DF		Allowed
39F8		Allowed
39FE		Allowed
3A18		Allowed
3A52		Allowed
3A5C		Allowed
3A67		Allowed
3A73		Allowed
3B39		Allowed
3B4E		Allowed
3BA3		Allowed
3C6E		Allowed
3CE0		Allowed
3DE7		Allowed
3DEB		Allowed
3E74		Allowed
3ED0		Allowed
4056		Allowed
4065		Allowed
406A		Allowed
40BB		Allowed
40DF		Allowed
4137		Allowed
415F		Allowed
4337		Allowed
43AC		Allowed
43B1		Allowed
43D3		Allowed
43DD		Allowed
4443		Allowed
44D6		Allowed
44EA		Allowed
4606		Allowed
464C		Allowed
4661		Allowed
4723		Allowed
4729		Allowed
477C		Allowed
478D		Allowed
47F4		Allowed
4882		Allowed
4947		Allowed
497A		Allowed
497D		Allowed
4982	4983	Allowed
4985	4986	Allowed
499B		Allowed
499F		Allowed
49B6	49B7	Allowed
4A12		Allowed
4AB8		Allowed
4C77		Allowed
4C7D		Allowed
4C81		Allowed
4C85		Allowed
4C9D	4CA3	Allowed
4D13	4D19	Allowed
4DAE		Allowed
4E00	4E11	Allowed
4E13	4E28	Allowed
4E2A	4E67	Allowed
4E69	4E78	Allowed
4E7A	4E95	Allowed
4E97	4EA2	Allowed
4EA4	4EBB	Allowed
4EBD	4ECB	Allowed
4ECD	4EE6	Allowed
4EE8	4EF7	Allowed
4EFB		Allowed
4EFD		Allowed
4EFF	4F06	Allowed
4F08	4F15	Allowed
4F17	4F27	Allowed
4F29	4F30	Allowed
4F32	4F34	Allowed
4F36		Allowed
4F38	4F3F	Allowed
4F41	4F43	Allowed
4F45	4F70	Allowed
4F72	4F8B	Allowed
4F8D		Allowed
4F8F	4FA1	Allowed
4FA3	4FBC	Allowed
4FBE	4FC5	Allowed
4FC7		Allowed
4FC9	4FCB	Allowed
4FCD	4FE1	Allowed
4FE3	4FFB	Allowed
4FFE	500F	Allowed
5011	5033	Allowed
5035	5037	Allowed
5039	503C	Allowed
503E	5041	Allowed
5043	5051	Allowed
5053	5057	Allowed
5059	507B	Allowed
507D	5080	Allowed
5082	5092	Allowed
5094	5096	Allowed
5098	509E	Allowed
50A2	50B8	Allowed
50BA	50C2	Allowed
50C4	50D7	Allowed
50D9	50DE	Allowed
50E0		Allowed
50E3	50EA	Allowed
50EC	50F3	Allowed
50F5	50F6	Allowed
50F8	511A	Allowed
511C	5127	Allowed
5129	512A	Allowed
512C	5141	Allowed
5143	5149	Allowed
514B	514E	Allowed
5150	5152	Allowed
5154	5157	Allowed
5159	515F	Allowed
5161	5163	Allowed
5165	5171	Allowed
5173	517D	Allowed
517F	5182	Allowed
5185	518D	Allowed
518F	51A0	Allowed
51A2		Allowed
51A4	51AC	Allowed
51AE	51B7	Allowed
51B9		Allowed
51BB	51C1	Allowed
51C3	51D1	Allowed
51D4	51DE	Allowed
51E0	51EB	Allowed
51ED		Allowed
51EF	51F1	Allowed
51F3	5252	Allowed
5254	5265	Allowed
5267	5278	Allowed
527A	5284	Allowed
5286	528D	Allowed
528F	52C3	Allowed
52C5	52C7	Allowed
52C9	52CB	Allowed
52CD		Allowed
52CF	52D0	Allowed
52D2	52D3	Allowed
52D5	52E0	Allowed
52E2	52E4	Allowed
52E6	52ED	Allowed
52EF	5302	Allowed
5305	5317	Allowed
5319	531A	Allowed
531C	531D	Allowed
531F	5326	Allowed
5328		Allowed
532A	5331	Allowed
5333	5334	Allowed
5337	5341	Allowed
5343	535A	Allowed
535C		Allowed
535E	5369	Allowed
536B	536C	Allowed
536E	537F	Allowed
5381	53A0	Allowed
53A2	53A9	Allowed
53AC	53AE	Allowed
53B0	53B9	Allowed
53BB	53C4	Allowed
53C6	53CE	Allowed
53D0	53DC	Allowed
53DF	53E6	Allowed
53E8	53FE	Allowed
5401	5419	Allowed
541B	5421	Allowed
5423	544B	Allowed
544D	545C	Allowed
545E	5468	Allowed
546A	5489	Allowed
548B	54B4	Allowed
54B6	54F5	Allowed
54F7	5514	Allowed
5516	5517	Allowed
551A	5546	Allowed
5548	555F	Allowed
5561	5579	Allowed
557B	55DF	Allowed
55E1	55F7	Allowed
55F9	5609	Allowed
560C	561F	Allowed
5621	562A	Allowed
562C	5636	Allowed
5638	563B	Allowed
563D	5643	Allowed
5645	564A	Allowed
564C	5650	Allowed
5652	5655	Allowed
5657	565E	Allowed
5660		Allowed
5662	5674	Allowed
5676	567C	Allowed
567E	5687	Allowed
5689	568A	Allowed
568C	5695	Allowed
5697	569D	Allowed
569F	56B9	Allowed
56BB	56CE	Allowed
56D0	56D8	Allowed
56DA	56E5	Allowed
56E7	56F5	Allowed
56F7		Allowed
56F9	56FA	Allowed
56FD	5704	Allowed
5706	5710	Allowed
5712	5716	Allowed
5718	5720	Allowed
5722	5723	Allowed
5725	573C	Allowed
573E	5742	Allowed
5744	5747	Allowed
5749	5754	Allowed
5757		Allowed
5759	5762	Allowed
5764	5777	Allowed
5779	5780	Allowed
5782	5786	Allowed
5788	5795	Allowed
5797	57A7	Allowed
57A9	57C9	Allowed
57CB	57D0	Allowed
57D2	57DA	Allowed
57DC	5816	Allowed
5819	584F	Allowed
5851	5855	Allowed
5857	585F	Allowed
5861	5865	Allowed
5868	5876	Allowed
5878	5894	Allowed
5896	58A9	Allowed
58AB	58B5	Allowed
58B7	58BF	Allowed
58C1	58C2	Allowed
58C5	58CC	Allowed
58CE	58CF	Allowed
58D1	58E0	Allowed
58E2	58E5	Allowed
58E7	58F4	Allowed
58F6	5900	Allowed
5902	5904	Allowed
5906	5907	Allowed
5909	5910	Allowed
5912		Allowed
5914	5922	Allowed
5924	5932	Allowed
5934	5935	Allowed
5937	5958	Allowed
595A		Allowed
595C	59B6	Allowed
59B8	59E6	Allowed
59E8	5A23	Allowed
5A25		Allowed
5A27	5A2B	Allowed
5A2D	5A2F	Allowed
5A31	5A53	Allowed
5A55	5A58	Allowed
5A5A	5A6E	Allowed
5A70		Allowed
5A72	5A86	Allowed
5A88	5A8C	Allowed
5A8E	5AAA	Allowed
5AAC	5AD2	Allowed
5AD4	5AEE	Allowed
5AF1	5B09	Allowed
5B0B	5B0C	Allowed
5B0E	5B38	Allowed
5B3A	5B45	Allowed
5B47	5B4E	Allowed
5B50	5B51	Allowed
5B53	5B5F	Allowed
5B62	5B6E	Allowed
5B70	5B78	Allowed
5B7A	5B7D	Allowed
5B7F	5B85	Allowed
5B87	5B8F	Allowed
5B91	5BA8	Allowed
5BAA	5BB1	Allowed
5BB3	5BB6	Allowed
5BB8	5BBB	Allowed
5BBD	5BC7	Allowed
5BC9	5BD9	Allowed
5BDB	5BFF	Allowed
5C01	5C1A	Allowed
5C1C	5C22	Allowed
5C24	5C25	Allowed
5C27	5C28	Allowed
5C2A	5C35	Allowed
5C37	5C59	Allowed
5C5B	5C84	Allowed
5C86	5CB3	Allowed
5CB5	5CB8	Allowed
5CBA	5CD4	Allowed
5CD6	5CDC	Allowed
5CDE	5CF4	Allowed
5CF6	5D2A	Allowed
5D2C	5D2E	Allowed
5D30	5D3A	Allowed
5D3C	5D52	Allowed
5D54	5D56	Allowed
5D58	5D5F	Allowed
5D61	5D82	Allowed
5D84	5D95	Allowed
5D97	5DA2	Allowed
5DA5	5DAA	Allowed
5DAC	5DB2	Allowed
5DB4	5DB8	Allowed
5DBA	5DC3	Allowed
5DC5	5DD6	Allowed
5DD8	5DD9	Allowed
5DDB		Allowed
5DDD	5DF5	Allowed
5DF7	5E11	Allowed
5E13	5E47	Allowed
5E49	5E50	Allowed
5E52	5E91	Allowed
5E93	5EB9	Allowed
5EBB	5EBF	Allowed
5EC1	5EEA	Allowed
5EEC	5EF8	Allowed
5EFA	5F0D	Allowed
5F0F	5F3A	Allowed
5F3C		Allowed
5F3E	5F8E	Allowed
5F90	5F99	Allowed
5F9B	5FA2	Allowed
5FA5	5FAF	Allowed
5FB1	5FC1	Allowed
5FC3	5FCD	Allowed
5FCF	5FDA	Allowed
5FDC	5FE1	Allowed
5FE3	5FEB	Allowed
5FED	5FFB	Allowed
5FFD	6022	Allowed
6024	6055	Allowed
6057	6060	Allowed
6062	6070	Allowed
6072	6073	Allowed
6075	6090	Allowed
6092		Allowed
6094	60A4	Allowed
60A6	60D1	Allowed
60D3	60D5	Allowed
60D7	60DD	Allowed
60DF	60E4	Allowed
60E6	60FC	Allowed
60FE	6101	Allowed
6103	6106	Allowed
6108	6110	Allowed
6112	611D	Allowed
611F	6130	Allowed
6132		Allowed
6134		Allowed
6136	6137	Allowed
613A	615F	Allowed
6161	617A	Allowed
617C	617E	Allowed
6180	6185	Allowed
6187	6196	Allowed
6198	619B	Allowed
619D	61B8	Allowed
61BA		Allowed
61BC	61D2	Allowed
61D4		Allowed
61D6	61EB	Allowed
61ED	61EE	Allowed
61F0	6204	Allowed
6206	6234	Allowed
6236	6238	Allowed
623A	6256	Allowed
6258	628C	Allowed
628E	629C	Allowed
629E	62DD	Allowed
62DF	62E9	Allowed
62EB	6309	Allowed
630B	6316	Allowed
6318	6330	Allowed
6332	6336	Allowed
6338	635A	Allowed
635C	638A	Allowed
638C	6392	Allowed
6394	63D0	Allowed
63D2	643A	Allowed
643D	6448	Allowed
644A	6459	Allowed
645B	647D	Allowed
647F	6485	Allowed
6487	64A0	Allowed
64A2	64AE	Allowed
64B0	64B5	Allowed
64B7	64C7	Allowed
64C9	64D4	Allowed
64D6	64ED	Allowed
64EF	64F4	Allowed
64F6	64F8	Allowed
64FA	6501	Allowed
6503	6509	Allowed
650B	651E	Allowed
6520	6527	Allowed
6529	653F	Allowed
6541		Allowed
6543	6559	Allowed
655B	655E	Allowed
6560	657C	Allowed
657E	6589	Allowed
658B	6599	Allowed
659B	65B4	Allowed
65B6	65BD	Allowed
65BF	65C7	Allowed
65CA	65D0	Allowed
65D2	65D7	Allowed
65D9	65DB	Allowed
65DD	65E3	Allowed
65E5	65E9	Allowed
65EB	65F8	Allowed
65FA	65FD	Allowed
65FF	6616	Allowed
6618	662B	Allowed
662D	6636	Allowed
6639	6647	Allowed
6649	664C	Allowed
664E	665F	Allowed
6661	6662	Allowed
6664	6691	Allowed
6693	669B	Allowed
669D		Allowed
669F	66AB	Allowed
66AE	66CF	Allowed
66D1	66D2	Allowed
66D4	66D6	Allowed
66D8	66DE	Allowed
66E0	66EE	Allowed
66F0	6701	Allowed
6703	6706	Allowed
6708	6718	Allowed
671A	6723	Allowed
6725	6728	Allowed
672A	6766	Allowed
6768	6787	Allowed
6789	6795	Allowed
6797	67BC	Allowed
67BE		Allowed
67C0	67D4	Allowed
67D6		Allowed
67D8	67F8	Allowed
67FA	6800	Allowed
6802	6814	Allowed
6816	6826	Allowed
6828	682F	Allowed
6831	6857	Allowed
6859		Allowed
685B	685D	Allowed
685F	6879	Allowed
687B	6894	Allowed
6896	6898	Allowed
689A	68A4	Allowed
68A6	68B7	Allowed
68B9	68C2	Allowed
68C4	68D8	Allowed
68DA	68E1	Allowed
68E3	68E4	Allowed
68E6	6908	Allowed
690A	693D	Allowed
693F	694C	Allowed
694E	699E	Allowed
69A0	69A1	Allowed
69A3	69BF	Allowed
69C1	69D0	Allowed
69D3	69D4	Allowed
69D8	6A02	Allowed
6A04	6A1B	Allowed
6A1D	6A23	Allowed
6A25	6A36	Allowed
6A38	6A49	Allowed
6A4B	6A5B	Allowed
6A5D	6A6D	Allowed
6A6F		Allowed
6A71	6A85	Allowed
6A87	6A89	Allowed
6A8B	6A8E	Allowed
6A90	6A98	Allowed
6A9A	6A9C	Allowed
6A9E	6AB0	Allowed
6AB2	6ABD	Allowed
6ABF		Allowed
6AC1	6AC3	Allowed
6AC5	6AC8	Allowed
6ACA	6AD7	Allowed
6AD9	6AE8	Allowed
6AEA	6B0D	Allowed
6B0F	6B1A	Allowed
6B1C	6B2D	Allowed
6B2F	6B34	Allowed
6B36	6B3F	Allowed
6B41	6B56	Allowed
6B59	6B5C	Allowed
6B5E	6B67	Allowed
6B69	6B6B	Allowed
6B6D		Allowed
6B6F	6B70	Allowed
6B72	6B74	Allowed
6B76	6B7C	Allowed
6B7E	6BB7	Allowed
6BB9	6BE8	Allowed
6BEA	6BF0	Allowed
6BF2	6BF3	Allowed
6BF5	6BF9	Allowed
6BFB	6C09	Allowed
6C0B	6C1B	Allowed
6C1D	6C2C	Allowed
6C2E	6C3B	Allowed
6C3D	6C44	Allowed
6C46	6C6B	Allowed
6C6D		Allowed
6C6F	6C9F	Allowed
6CA1	6CD7	Allowed
6CD9	6CF3	Allowed
6CF5	6D01	Allowed
6D03	6D1B	Allowed
6D1D	6D23	Allowed
6D25	6D70	Allowed
6D72	6D80	Allowed
6D82	6D95	Allowed
6D97	6DAF	Allowed
6DB2	6DB5	Allowed
6DB7	6DFD	Allowed
6E00		Allowed
6E03	6E05	Allowed
6E07	6E11	Allowed
6E13	6E17	Allowed
6E19	6E29	Allowed
6E2B	6E4B	Allowed
6E4D	6E6B	Allowed
6E6D	6E7A	Allowed
6E7E	6E8A	Allowed
6E8C	6E94	Allowed
6E96	6EDA	Allowed
6EDC	6EE2	Allowed
6EE4	6F03	Allowed
6F05	6F0A	Allowed
6F0C	6F41	Allowed
6F43	6F47	Allowed
6F49		Allowed
6F4B	6F78	Allowed
6F7A	6F97	Allowed
6F99		Allowed
6F9B	6F9E	Allowed
6FA0	6FB6	Allowed
6FB8	6FC4	Allowed
6FC6	6FCF	Allowed
6FD1	6FD2	Allowed
6FD4	6FF4	Allowed
6FF6	6FFC	Allowed
6FFE	700F	Allowed
7011	7012	Allowed
7014	7046	Allowed
7048	704A	Allowed
704C	704D	Allowed
704F	7071	Allowed
7074	707A	Allowed
707C	7080	Allowed
7082	708C	Allowed
708E	7096	Allowed
7098	709A	Allowed
709C	70A9	Allowed
70AB	70B1	Allowed
70B3	70B5	Allowed
70B7	70D4	Allowed
70D6	70FD	Allowed
70FF	7107	Allowed
7109	7123	Allowed
7125	7132	Allowed
7135	7156	Allowed
7158	716A	Allowed
716C		Allowed
716E	718C	Allowed
718E	7195	Allowed
7197	71A5	Allowed
71A7	71AA	Allowed
71AC	71B5	Allowed
71B7	71CB	Allowed
71CD	71D2	Allowed
71D4	71F2	Allowed
71F4	71F9	Allowed
71FB	720A	Allowed
720C	7210	Allowed
7212	7214	Allowed
7216		Allowed
7218	721F	Allowed
7221	7223	Allowed
7226	722E	Allowed
7230	7233	Allowed
7235	7244	Allowed
7246	724D	Allowed
724F		Allowed
7251	7254	Allowed
7256	72AA	Allowed
72AC	72BD	Allowed
72BF	7301	Allowed
7303	730F	Allowed
7311	7327	Allowed
7329	7352	Allowed
7354	739B	Allowed
739D	73C0	Allowed
73C2	73F2	Allowed
73F4	73FA	Allowed
73FC	7417	Allowed
7419	7438	Allowed
743A	743D	Allowed
743F	7446	Allowed
7448		Allowed
744A	7457	Allowed
7459	747A	Allowed
747C	7483	Allowed
7485	7495	Allowed
7497	749C	Allowed
749E	74C6	Allowed
74C8		Allowed
74CA	74CB	Allowed
74CD	74EA	Allowed
74EC	751F	Allowed
7521	7540	Allowed
7542	7551	Allowed
7553	7554	Allowed
7556	755D	Allowed
755F	7560	Allowed
7562	7570	Allowed
7572	757A	Allowed
757C	7584	Allowed
7586	75A8	Allowed
75AA	75B6	Allowed
75B8	75DB	Allowed
75DD	75ED	Allowed
75EF	762B	Allowed
762D	7643	Allowed
7646	7650	Allowed
7652	7654	Allowed
7656	7672	Allowed
7674	768C	Allowed
768E	76A0	Allowed
76A3	76A4	Allowed
76A6	76A7	Allowed
76A9	76B2	Allowed
76B4	76B5	Allowed
76B7	76C0	Allowed
76C2	76CA	Allowed
76CC	76D8	Allowed
76DA	76EA	Allowed
76EC	76FF	Allowed
7701		Allowed
7703	770D	Allowed
770F	7720	Allowed
7722	772A	Allowed
772C	773E	Allowed
7740	7741	Allowed
7743	7763	Allowed
7765	7795	Allowed
7797	77A3	Allowed
77A5	77BD	Allowed
77BF	77C0	Allowed
77C2	77D1	Allowed
77D3	77DC	Allowed
77DE	77E3	Allowed
77E5		Allowed
77E7	77F3	Allowed
77F6	7823	Allowed
7825	7835	Allowed
7837	7841	Allowed
7843	7845	Allowed
7847	784A	Allowed
784C	7875	Allowed
7877	7887	Allowed
7889	78C1	Allowed
78C3	78C6	Allowed
78C8	78D1	Allowed
78D3	78EF	Allowed
78F1	78F7	Allowed
78F9	78FF	Allowed
7901	7907	Allowed
7909	790C	Allowed
790E	7914	Allowed
7916	791E	Allowed
7921	7931	Allowed
7933	7935	Allowed
7937	7958	Allowed
795A	796B	Allowed
796D		Allowed
796F	7974	Allowed
7977	7985	Allowed
7988	799D	Allowed
799F	79A8	Allowed
79AA	79BB	Allowed
79BD	79C3	Allowed
79C5	79C6	Allowed
79C8	79CB	Allowed
79CD	79D3	Allowed
79D5	79D6	Allowed
79D8	7A00	Allowed
7A02	7A06	Allowed
7A08		Allowed
7A0A	7A2B	Allowed
7A2D	7A37	Allowed
7A39		Allowed
7A3B	7A63	Allowed
7A65	7A69	Allowed
7A6B	7A6E	Allowed
7A70	7A81	Allowed
7A83	7A99	Allowed
7A9C	7AB8	Allowed
7ABA		Allowed
7ABE	7AC1	Allowed
7AC3	7AC5	Allowed
7AC7	7AE8	Allowed
7AEA	7AF4	Allowed
7AF6	7AFB	Allowed
7AFD	7B06	Allowed
7B08	7B1E	Allowed
7B20	7B26	Allowed
7B28		Allowed
7B2A	7B41	Allowed
7B43	7B52	Allowed
7B54	7BA2	Allowed
7BA4		Allowed
7BA6	7BAF	Allowed
7BB1		Allowed
7BB3	7BF9	Allowed
7BFB	7C1A	Allowed
7C1C	7C2D	Allowed
7C30	7C51	Allowed
7C53	7C54	Allowed
7C56	7C5C	Allowed
7C5E	7C75	Allowed
7C77	7C86	Allowed
7C88	7C92	Allowed
7C94	7C99	Allowed
7C9B	7CAB	Allowed
7CAD	7CD2	Allowed
7CD4	7CD9	Allowed
7CDC	7CE0	Allowed
7CE2		Allowed
7CE4		Allowed
7CE7	7CFB	Allowed
7CFD	7CFE	Allowed
7D00	7D22	Allowed
7D24	7D29	Allowed
7D2B	7D2C	Allowed
7D2E	7D47	Allowed
7D49	7D4C	Allowed
7D4E	7D59	Allowed
7D5B	7D63	Allowed
7D65	7D77	Allowed
7D79	7D81	Allowed
7D83	7D94	Allowed
7D96	7D97	Allowed
7D99	7DA3	Allowed
7DA5	7DA7	Allowed
7DA9	7DCC	Allowed
7DCE	7DD2	Allowed
7DD4	7DE4	Allowed
7DE6	7DEA	Allowed
7DEC	7DFC	Allowed
7E00	7E17	Allowed
7E19	7E5A	Allowed
7E5C	7E63	Allowed
7E65	7E9C	Allowed
7E9E	7F3A	Allowed
7F3D	7F40	Allowed
7F42	7F45	Allowed
7F47	7F58	Allowed
7F5A	7F83	Allowed
7F85	7F8F	Allowed
7F91	7F96	Allowed
7F98		Allowed
7F9A	7FB3	Allowed
7FB5	7FD5	Allowed
7FD7	7FDC	Allowed
7FDE	7FE3	Allowed
7FE5	8009	Allowed
800B	802E	Allowed
8030	803B	Allowed
803D	803F	Allowed
8041	8065	Allowed
8067	8087	Allowed
8089	808D	Allowed
808F	8093	Allowed
8095	80A5	Allowed
80A9	80B2	Allowed
80B4	80B8	Allowed
80BA	80DE	Allowed
80E0	8102	Allowed
8105	8133	Allowed
8136	8183	Allowed
8185	818F	Allowed
8191	8195	Allowed
8197	81CA	Allowed
81CC	81E3	Allowed
81E5	81EE	Allowed
81F1	8212	Allowed
8214	8223	Allowed
8225	8240	Allowed
8242	8264	Allowed
8266	828B	Allowed
828D	82B1	Allowed
82B3	82E1	Allowed
82E3	82FB	Allowed
82FD	8309	Allowed
830B	830F	Allowed
8311	832F	Allowed
8331	8354	Allowed
8356	83BD	Allowed
83BF	83E5	Allowed
83E7	83EC	Allowed
83EE	8413	Allowed
8415		Allowed
8418	841E	Allowed
8420	8457	Allowed
8459	8482	Allowed
8484	8494	Allowed
8496	84B6	Allowed
84B8	84C2	Allowed
84C4	84EC	Allowed
84EE	8504	Allowed
8506	850F	Allowed
8511	8531	Allowed
8534	854B	Allowed
854D	854F	Allowed
8551	857E	Allowed
8580	8592	Allowed
8594	85B1	Allowed
85B3	85BA	Allowed
85BC	85CB	Allowed
85CD	85ED	Allowed
85EF	85F2	Allowed
85F4	85FB	Allowed
85FD	8602	Allowed
8604	860C	Allowed
860F		Allowed
8611	8614	Allowed
8616	861C	Allowed
861E	8636	Allowed
8638	8656	Allowed
8658	8674	Allowed
8676	8688	Allowed
868A	8691	Allowed
8693	869F	Allowed
86A1	86A5	Allowed
86A7	86D4	Allowed
86D6	86DF	Allowed
86E1	86E6	Allowed
86E8	86FC	Allowed
86FE	871C	Allowed
871E	872E	Allowed
8730	873C	Allowed
873E	8744	Allowed
8746	8770	Allowed
8772	878D	Allowed
878F	8798	Allowed
879A	87D9	Allowed
87DB	87EF	Allowed
87F1	8806	Allowed
8808	8811	Allowed
8813	882C	Allowed
882E	8839	Allowed
883B	8846	Allowed
8848	8857	Allowed
8859	885B	Allowed
885D	885E	Allowed
8860	8879	Allowed
887B	88E5	Allowed
88E7	88E8	Allowed
88EA	88EC	Allowed
88EE	8902	Allowed
8904	890E	Allowed
8910	8923	Allowed
8925	8964	Allowed
8966	8974	Allowed
8976	897C	Allowed
897E	898C	Allowed
898E	898F	Allowed
8991	8993	Allowed
8995	8998	Allowed
899A	89AF	Allowed
89B1	89B3	Allowed
89B5	89BA	Allowed
89BD	89ED	Allowed
89EF	89F4	Allowed
89F6	89F8	Allowed
89FA	89FC	Allowed
89FE	8A04	Allowed
8A07	8A13	Allowed
8A15	8A18	Allowed
8A1A	8A1F	Allowed
8A22	8A2A	Allowed
8A2C	8A3C	Allowed
8A3E	8A4A	Allowed
8A4C	8A63	Allowed
8A65	8A77	Allowed
8A79	8A7C	Allowed
8A7E	8A87	Allowed
8A89	8A9E	Allowed
8AA0	8AAE	Allowed
8AB0	8AB6	Allowed
8AB8	8ACF	Allowed
8AD1	8AEB	Allowed
8AED	8B28	Allowed
8B2A	8B31	Allowed
8B33	8B37	Allowed
8B39	8B3E	Allowed
8B40	8B60	Allowed
8B63	8B68	Allowed
8B6A	8B74	Allowed
8B76	8B7B	Allowed
8B7D	8B80	Allowed
8B82	8B86	Allowed
8B88	8B8C	Allowed
8B8E		Allowed
8B90	8B9A	Allowed
8B9C	8C37	Allowed
8C39	8C3F	Allowed
8C41	8C43	Allowed
8C45	8C50	Allowed
8C54	8C57	Allowed
8C59	8C73	Allowed
8C75	8C7E	Allowed
8C80	8C82	Allowed
8C84	8C86	Allowed
8C88	8C8A	Allowed
8C8C	8C9A	Allowed
8C9C	8CA5	Allowed
8CA7	8CCA	Allowed
8CCC	8CD5	Allowed
8CD7		Allowed
8CD9	8CE8	Allowed
8CEA	8CF6	Allowed
8CF8	8D00	Allowed
8D02	8D10	Allowed
8D13	8D7B	Allowed
8D7D	8DA5	Allowed
8DA7	8DBF	Allowed
8DC1	8DE4	Allowed
8DE6	8E00	Allowed
8E02	8E0A	Allowed
8E0C	8E31	Allowed
8E33	8E45	Allowed
8E47	8E4E	Allowed
8E50	8E6D	Allowed
8E6F	8E74	Allowed
8E76		Allowed
8E78		Allowed
8E7A	8E9A	Allowed
8E9C	8EA1	Allowed
8EA3	8EB2	Allowed
8EB4	8EB5	Allowed
8EB8	8EC0	Allowed
8EC2	8EC3	Allowed
8EC5	8ED8	Allowed
8EDA	8EEF	Allowed
8EF1	8F0E	Allowed
8F10	8F2C	Allowed
8F2E	8F39	Allowed
8F3B	8F40	Allowed
8F42	8F9C	Allowed
8F9E	8FA3	Allowed
8FA5	8FB2	Allowed
8FB4	8FC2	Allowed
8FC4	8FC9	Allowed
8FCB	8FE6	Allowed
8FE8	9029	Allowed
902B		Allowed
902D	9036	Allowed
9038	903F	Allowed
9041	9045	Allowed
9047	90AA	Allowed
90AC	90CB	Allowed
90CE	90D1	Allowed
90D3	90F5	Allowed
90F7	9109	Allowed
910B	913B	Allowed
913E	9158	Allowed
915A	917A	Allowed
917C	9194	Allowed
9196	9197	Allowed
9199	91A8	Allowed
91AA	91BE	Allowed
91C0	91C3	Allowed
91C5	91DF	Allowed
91E1	91EE	Allowed
91F0	9212	Allowed
9214	921E	Allowed
9220	9221	Allowed
9223	9242	Allowed
9244	9268	Allowed
926B	9280	Allowed
9282	9283	Allowed
9285	929D	Allowed
929F	92BC	Allowed
92BE	92D3	Allowed
92D5	92DA	Allowed
92DC	92E1	Allowed
92E3	931B	Allowed
931D	932F	Allowed
9332	9361	Allowed
9363	9367	Allowed
9369	936A	Allowed
936C	936E	Allowed
9370	9372	Allowed
9374	9377	Allowed
9379	937E	Allowed
9380		Allowed
9382	938A	Allowed
938C	939B	Allowed
939D	939F	Allowed
93A1	93AA	Allowed
93AC	93BA	Allowed
93BC	93DF	Allowed
93E1	93F2	Allowed
93F4	9401	Allowed
9403	9416	Allowed
9418	941B	Allowed
941D		Allowed
9420	9423	Allowed
9425	9442	Allowed
9444	944D	Allowed
944F	946B	Allowed
946D	947A	Allowed
947C	9577	Allowed
957A	957D	Allowed
957F	9584	Allowed
9586	9596	Allowed
9598	95B2	Allowed
95B5	95B7	Allowed
95B9	95C0	Allowed
95C2	95D8	Allowed
95DA	95DC	Allowed
95DE	9624	Allowed
9627	9628	Allowed
962A	963D	Allowed
963F	9655	Allowed
9658	9678	Allowed
967A		Allowed
967C	967E	Allowed
9680		Allowed
9683	968B	Allowed
968D	9695	Allowed
9697	9699	Allowed
969B	969C	Allowed
969E		Allowed
96A0	96AA	Allowed
96AC	96AE	Allowed
96B0	96B4	Allowed
96B6	96E3	Allowed
96E5		Allowed
96E8	96FB	Allowed
96FD	9713	Allowed
9715	9716	Allowed
9718	9719	Allowed
971C	9732	Allowed
9735	9736	Allowed
9738	973F	Allowed
9742	974C	Allowed
974E	9756	Allowed
9758	9762	Allowed
9764	9774	Allowed
9776	9786	Allowed
9788		Allowed
978A	979A	Allowed
979C	97A8	Allowed
97AA	97AF	Allowed
97B2	97B4	Allowed
97B6	97BD	Allowed
97BF		Allowed
97C1	97D1	Allowed
97D3	97FB	Allowed
97FD	981E	Allowed
9820	9824	Allowed
9826	9829	Allowed
982B	9832	Allowed
9834	9839	Allowed
983B	983D	Allowed
983F	9841	Allowed
9843	9846	Allowed
9848	9855	Allowed
9857	9865	Allowed
9867		Allowed
9869	98B6	Allowed
98B8	98C9	Allowed
98CB	98E3	Allowed
98E5	98EB	Allowed
98ED	98F0	Allowed
98F2	98F7	Allowed
98F9	98FA	Allowed
98FC	9918	Allowed
991A	993A	Allowed
993C	9943	Allowed
9945	9959	Allowed
995B	995C	Allowed
995E	99BE	Allowed
99C0	99DF	Allowed
99E1	99E5	Allowed
99E7	99EA	Allowed
99EC	99F4	Allowed
99F6	9A0F	Allowed
9A11	9A16	Allowed
9A19	9A3A	Allowed
9A3C	9A50	Allowed
9A52	9A57	Allowed
9A59	9A5C	Allowed
9A5E	9A62	Allowed
9A64	9AA8	Allowed
9AAA	9ABC	Allowed
9ABE	9AC7	Allowed
9AC9	9AD6	Allowed
9AD8	9ADF	Allowed
9AE1	9AE3	Allowed
9AE5	9AE7	Allowed
9AEA	9AEF	Allowed
9AF1	9AFF	Allowed
9B01		Allowed
9B03	9B08	Allowed
9B0A	9B13	Allowed
9B15	9B1A	Allowed
9B1C	9B33	Allowed
9B35	9B3C	Allowed
9B3E	9B3F	Allowed
9B41	9B4F	Allowed
9B51	9B56	Allowed
9B58	9B61	Allowed
9B63	9B71	Allowed
9B73	9B88	Allowed
9B8A	9B8B	Allowed
9B8D	9B98	Allowed
9B9A	9BC1	Allowed
9BC3	9BF5	Allowed
9BF7	9BFF	Allowed
9C02		Allowed
9C04	9C41	Allowed
9C43	9C4E	Allowed
9C50		Allowed
9C52	9C60	Allowed
9C62	9C63	Allowed
9C65	9C7A	Allowed
9C7C	9D0B	Allowed
9D0E	9D10	Allowed
9D12	9D26	Allowed
9D28	9D34	Allowed
9D36	9D3B	Allowed
9D3D	9D6C	Allowed
9D6E	9D94	Allowed
9D96	9DAD	Allowed
9DAF	9DBC	Allowed
9DBE	9DBF	Allowed
9DC1	9DE9	Allowed
9DEB	9DFB	Allowed
9DFD	9E0D	Allowed
9E0F	9E15	Allowed
9E17	9E1B	Allowed
9E1D	9E7A	Allowed
9E7C	9E8E	Allowed
9E91	9E97	Allowed
9E99	9E9D	Allowed
9E9F	9EA1	Allowed
9EA3	9EAA	Allowed
9EAD	9EB0	Allowed
9EB2	9EEB	Allowed
9EED	9EF0	Allowed
9EF2	9F02	Allowed
9F04	9F10	Allowed
9F12	9F13	Allowed
9F15	9F25	Allowed
9F27	9F44	Allowed
9F46	9F52	Allowed
9F54	9F6C	Allowed
9F6E	9FA0	Allowed
9FA2		Allowed
9FA4	9FA5	Allowed
A78D		Allowed
A7AA		Allowed
AA7B		Allowed
AC00	D7A3	Allowed
11301		Allowed
11303		Allowed
1133C		Allowed
1E7E0	1E7E6	Allowed
1E7E8	1E7EB	Allowed
1E7ED	1E7EE	Allowed
1E7F0	1E7FE	Allowed
2070E		Allowed
20731		Allowed
20779		Allowed
20C53		Allowed
20C78		Allowed
20C96		Allowed
20CCF		Allowed
20CD5		Allowed
20D15		Allowed
20D7C		Allowed
20D7F		Allowed
20E0E	20E0F	Allowed
20E77		Allowed
20E9D		Allowed
20EA2		Allowed
20ED7		Allowed
20EF9	20EFA	Allowed
20F2D	20F2E	Allowed
20F4C		Allowed
20FB4		Allowed
20FBC		Allowed
20FEA		Allowed
2105C		Allowed
2106F		Allowed
21075	21076	Allowed
2107B		Allowed
210C1		Allowed
210C9		Allowed
211D9		Allowed
220C7		Allowed
227B5		Allowed
22AD5		Allowed
22B43		Allowed
22BCA		Allowed
22C51		Allowed
22C55		Allowed
22CC2		Allowed
22D08		Allowed
22D4C		Allowed
22D67		Allowed
22EB3		Allowed
23CB7		Allowed
244D3		Allowed
24DB8		Allowed
24DEA		Allowed
2512B		Allowed
26258		Allowed
267CC		Allowed
269F2		Allowed
269FA		Allowed
27A3E		Allowed
2815D		Allowed
28207		Allowed
282E2		Allowed
28CCA		Allowed
28CCD		Allowed
28CD2		Allowed
29D98		Allowed
END
