# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 17.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


# The mappings in the non-hash portion of this file must be modified to get the
# correct values by adding the code point ordinal number to each one that is
# numeric.

# The name this table is to be known by, with the format of the mappings in
# the main body of the table, and what all code points missing from this file
# map to.
$Unicode::UCD::SwashInfo{'TokEHAltSeq'}{'format'} = 'ax'; # mapped value in hex; some entries need adjustment
$Unicode::UCD::SwashInfo{'TokEHAltSeq'}{'specials_name'} = 'Unicode::UCD::ToSpeckEHAltSeq'; # Name of hash of special mappings
$Unicode::UCD::SwashInfo{'TokEHAltSeq'}{'missing'} = '0'; # code point maps to itself

# Some code points require special handling because their mappings are each to
# multiple code points.  These do not appear in the main body, but are defined
# in the hash below.

# Each key is the string of N bytes that together make up the UTF-8 encoding
# for the code point.  (i.e. the same as looking at the code point's UTF-8
# under "use bytes").  Each value is the UTF-8 of the translation, for speed.
%Unicode::UCD::ToSpeckEHAltSeq = (
"\xF0\x93\x81\x9D" => "\x{1305C}\x{13440}",   # U+1305D => 1305C 13440
"\xF0\x93\x81\x9E" => "\x{1305B}\x{13440}",   # U+1305E => 1305B 13440
"\xF0\x93\x81\xAA" => "\x{13069}\x{13440}",   # U+1306A => 13069 13440
"\xF0\x93\x81\xAC" => "\x{1306B}\x{13440}",   # U+1306C => 1306B 13440
"\xF0\x93\x82\x96" => "\x{13098}\x{1343B}\x{1335B}", # U+13096 => 13098 1343B 1335B
"\xF0\x93\x82\x97" => "\x{13093}\x{1343A}\x{1335B}", # U+13097 => 13093 1343A 1335B
"\xF0\x93\x82\xB9" => "\x{130B8}\x{13436}\x{132F4}", # U+130B9 => 130B8 13436 132F4
"\xF0\x93\x83\x81" => "\x{1309D}\x{13436}\x{130C0}", # U+130C1 => 1309D 13436 130C0
"\xF0\x93\x84\x98" => "\x{13117}\x{13440}",   # U+13118 => 13117 13440
"\xF0\x93\x84\xB3" => "\x{13132}\x{FE01}",    # U+13133 => 13132 FE01
"\xF0\x93\x84\xB4" => "\x{13132}\x{13440}",   # U+13134 => 13132 13440
"\xF0\x93\x84\xB5" => "\x{13132}\x{FE01}\x{13440}", # U+13135 => 13132 FE01 13440
"\xF0\x93\x84\xB7" => "\x{13136}\x{13440}",   # U+13137 => 13136 13440
"\xF0\x93\x84\xB8" => "\x{13132}\x{13436}\x{132F4}", # U+13138 => 13132 13436 132F4
"\xF0\x93\x84\xBA" => "\x{13139}\x{13431}\x{13139}\x{13431}\x{13139}", # U+1313A => 13139 13431 13139 13431 13139
"\xF0\x93\x84\xBB" => "\x{13139}\x{13430}\x{13139}\x{13430}\x{13139}", # U+1313B => 13139 13430 13139 13430 13139
"\xF0\x93\x84\xBC" => "\x{13139}\x{FE01}",    # U+1313C => 13139 FE01
"\xF0\x93\x85\x81" => "\x{13333}\x{13436}\x{1313F}", # U+13141 => 13333 13436 1313F
"\xF0\x93\x85\x92" => "\x{13D04}\x{13431}\x{13D95}", # U+13152 => 13D04 13431 13D95
"\xF0\x93\x85\x95" => "\x{13153}\x{13436}\x{1309E}", # U+13155 => 13153 13436 1309E
"\xF0\x93\x85\x96" => "\x{13153}\x{13436}\x{1309D}", # U+13156 => 13153 13436 1309D
"\xF0\x93\x85\x97" => "\x{13153}\x{13436}\x{1308B}", # U+13157 => 13153 13436 1308B
"\xF0\x93\x85\xB2" => "\x{13171}\x{13433}\x{133CF}", # U+13172 => 13171 13433 133CF
"\xF0\x93\x85\xB4" => "\x{1309D}\x{13436}\x{13171}", # U+13174 => 1309D 13436 13171
"\xF0\x93\x85\xB5" => "\x{1309E}\x{13436}\x{13171}", # U+13175 => 1309E 13436 13171
"\xF0\x93\x85\xB6" => "\x{13333}\x{13436}\x{13171}", # U+13176 => 13333 13436 13171
"\xF0\x93\x86\x96" => "\x{13193}\x{13433}\x{13437}\x{133CF}\x{13430}\x{131FF}\x{13438}", # U+13196 => 13193 13433 13437 133CF 13430 131FF 13438
"\xF0\x93\x86\xA5" => "\x{131D3}\x{13431}\x{131A4}\x{13430}\x{133CF}\x{13431}\x{133CF}", # U+131A5 => 131D3 13431 131A4 13430 133CF 13431 133CF
"\xF0\x93\x86\xAA" => "\x{131A9}\x{13440}",   # U+131AA => 131A9 13440
"\xF0\x93\x86\xAE" => "\x{131B1}\x{13436}\x{131AD}", # U+131AE => 131B1 13436 131AD
"\xF0\x93\x86\xAF" => "\x{13191}\x{13436}\x{131AD}", # U+131AF => 13191 13436 131AD
"\xF0\x93\x86\xB2" => "\x{13153}\x{13436}\x{131B1}", # U+131B2 => 13153 13436 131B1
"\xF0\x93\x87\x86" => "\x{13193}\x{13436}\x{131C5}", # U+131C6 => 13193 13436 131C5
"\xF0\x93\x87\x98" => "\x{1309D}\x{13436}\x{131D7}", # U+131D8 => 1309D 13436 131D7
"\xF0\x93\x87\xA1" => "\x{131E0}\x{FE00}\x{13440}", # U+131E1 => 131E0 FE00 13440
"\xF0\x93\x88\x82" => "\x{13200}\x{13439}\x{13283}", # U+13202 => 13200 13439 13283
"\xF0\x93\x89\x91" => "\x{13250}\x{1343B}\x{132F9}", # U+13251 => 13250 1343B 132F9
"\xF0\x93\x89\x92" => "\x{13250}\x{1343B}\x{13309}", # U+13252 => 13250 1343B 13309
"\xF0\x93\x89\x96" => "\x{13255}\x{13440}",   # U+13256 => 13255 13440
"\xF0\x93\x89\x9E" => "\x{13257}\x{1343A}\x{133CF}", # U+1325E => 13257 1343A 133CF
"\xF0\x93\x89\x9F" => "\x{13257}\x{1343A}\x{133CF}\x{13436}\x{1327B}", # U+1325F => 13257 1343A 133CF 13436 1327B
"\xF0\x93\x89\xA0" => "\x{13F60}\x{13439}\x{133CF}", # U+13260 => 13F60 13439 133CF
"\xF0\x93\x89\xA1" => "\x{13257}\x{13439}\x{13143}", # U+13261 => 13257 13439 13143
"\xF0\x93\x89\xA2" => "\x{13257}\x{13439}\x{132F9}", # U+13262 => 13257 13439 132F9
"\xF0\x93\x89\xA3" => "\x{13257}\x{13439}\x{131A4}", # U+13263 => 13257 13439 131A4
"\xF0\x93\x89\xA4" => "\x{1326C}\x{13439}\x{13077}", # U+13264 => 1326C 13439 13077
"\xF0\x93\x89\xA6" => "\x{1309D}\x{13436}\x{13265}", # U+13266 => 1309D 13436 13265
"\xF0\x93\x89\xBC" => "\x{1327B}\x{FE00}",    # U+1327C => 1327B FE00
"\xF0\x93\x89\xBE" => "\x{1327D}\x{13431}\x{1327D}\x{13431}\x{1327D}\x{13431}\x{1327D}", # U+1327E => 1327D 13431 1327D 13431 1327D 13431 1327D
"\xF0\x93\x8A\x98" => "\x{13299}\x{13440}",   # U+13298 => 13299 13440
"\xF0\x93\x8A\xA3" => "\x{1309D}\x{13436}\x{132A2}", # U+132A3 => 1309D 13436 132A2
"\xF0\x93\x8A\xA5" => "\x{13191}\x{13436}\x{132A4}", # U+132A5 => 13191 13436 132A4
"\xF0\x93\x8B\x9F" => "\x{132DE}\x{13436}\x{130C0}", # U+132DF => 132DE 13436 130C0
"\xF0\x93\x8B\xA0" => "\x{132DE}\x{13436}\x{13309}", # U+132E0 => 132DE 13436 13309
"\xF0\x93\x8B\xA1" => "\x{132DE}\x{13436}\x{13300}", # U+132E1 => 132DE 13436 13300
"\xF0\x93\x8B\xB5" => "\x{13191}\x{13436}\x{132F4}", # U+132F5 => 13191 13436 132F4
"\xF0\x93\x8B\xB6" => "\x{13333}\x{13436}\x{132F4}", # U+132F6 => 13333 13436 132F4
"\xF0\x93\x8C\x8C" => "\x{13193}\x{13436}\x{13309}", # U+1330C => 13193 13436 13309
"\xF0\x93\x8C\x8D" => "\x{13193}\x{13433}\x{13193}\x{13436}\x{13309}", # U+1330D => 13193 13433 13193 13436 13309
"\xF0\x93\x8C\xAD" => "\x{1332B}\x{13436}\x{132F4}", # U+1332D => 1332B 13436 132F4
"\xF0\x93\x8C\xAF" => "\x{13333}\x{13432}\x{13079}", # U+1332F => 13333 13432 13079
"\xF0\x93\x8C\xB5" => "\x{13333}\x{13432}\x{13079}", # U+13335 => 13333 13432 13079
"\xF0\x93\x8C\xB6" => "\x{13333}\x{13432}\x{13419}", # U+13336 => 13333 13432 13419
"\xF0\x93\x8C\xB7" => "\x{13334}\x{13432}\x{13419}", # U+13337 => 13334 13432 13419
"\xF0\x93\x8C\xB9" => "\x{13338}\x{FE03}",    # U+13339 => 13338 FE03
"\xF0\x93\x8C\xBA" => "\x{13338}\x{FE03}\x{13440}", # U+1333A => 13338 FE03 13440
"\xF0\x93\x8C\xBB" => "\x{13338}\x{FE06}",    # U+1333B => 13338 FE06
"\xF0\x93\x8D\x93" => "\x{13351}\x{13436}\x{133F2}", # U+13353 => 13351 13436 133F2
"\xF0\x93\x8D\x9A" => "\x{13191}\x{13436}\x{13359}", # U+1335A => 13191 13436 13359
"\xF0\x93\x8E\x9C" => "\x{1309D}\x{13436}\x{1339B}", # U+1339C => 1309D 13436 1339B
"\xF0\x93\x8E\x9E" => "\x{133A1}\x{13436}\x{1339D}", # U+1339E => 133A1 13436 1339D
"\xF0\x93\x8E\xA2" => "\x{133A1}\x{13440}",   # U+133A2 => 133A1 13440
"\xF0\x93\x8E\xB9" => "\x{133B8}\x{13440}",   # U+133B9 => 133B8 13440
"\xF0\x93\x8F\x80" => "\x{1339B}\x{13431}\x{133BF}\x{13430}\x{13283}", # U+133C0 => 1339B 13431 133BF 13430 13283
"\xF0\x93\x8F\x8D" => "\x{133CC}\x{13431}\x{133CC}\x{13431}\x{133CC}", # U+133CD => 133CC 13431 133CC 13431 133CC
"\xF0\x93\x8F\x9C" => "\x{133DB}\x{FE02}",    # U+133DC => 133DB FE02
"\xF0\x93\x8F\x9F" => "\x{133DE}\x{13440}",   # U+133DF => 133DE 13440
"\xF0\x93\x8F\xA9" => "\x{133E8}\x{FE01}",    # U+133E9 => 133E8 FE01
"\xF0\x93\x8F\xAB" => "\x{133E5}\x{FE00}",    # U+133EB => 133E5 FE00
"\xF0\x93\x8F\xAC" => "\x{133E7}\x{FE00}",    # U+133EC => 133E7 FE00
"\xF0\x93\x90\x94" => "\x{13413}\x{13440}",   # U+13414 => 13413 13440
"\xF0\x93\x90\xA4" => "\x{1309D}\x{13436}\x{13423}", # U+13424 => 1309D 13436 13423
);

return <<'END';
13092		13091
130FA		130F9
1310C		1310B
13169		13168
1316B		1316A
131E2		131E0
1320A		13209
13215		13214
13270		1326F
132F1		132F0
132FB		132FA
133A0		1339F
133B2		133B1
133D7		133D6
13403		133FE
END
