#!/bin/sh
export PATH=/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/bin
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
ip link set lo up

echo "=================================================="
echo " Welcome to System Linux v0.1                     "
echo " Powered by: goget (Source-First Package Manager) "
echo "=================================================="
