// Code generated by go tool dist; DO NOT EDIT.

package cfg

const DefaultPkgConfig = `pkg-config`
func DefaultCC(goos, goarch string) string {
	switch goos+`/`+goarch {
	}
	return "x86_64-pc-linux-gnu-gcc"
}
func DefaultCXX(goos, goarch string) string {
	switch goos+`/`+goarch {
	}
	return "x86_64-pc-linux-gnu-g++"
}
