#!/usr/bin/python3.14
# -*- coding: utf-8 -*-
import re
import sys
from gemato.cli import setuptools_main
if __name__ == "__main__":
    sys.argv[0] = re.sub(r"(-script\.pyw|\.exe)?$", "", sys.argv[0])
    sys.exit(setuptools_main())
